### ISSUE TITLE
don't tell users to call House Representative for SCOTUS pick

### ISSUE THREAD

**Issue by lauren** [5calls/5calls#105]
SCOTUS nominees are only up for vote in the Senate, not the House. The House representative can't do anything about it.

https://www.nytimes.com/2017/01/31/us/politics/supreme-court-nomination-process.html

**Comment by davemacdo** [comment]
Agreed. This is a general thing the issues list should account for. Budget things go to the House, confirmation things to the Senate.

**Comment by nickoneill** [comment]
Whoops, we're usually on top of things like this. @rebeccakaufman will check it out

**Comment by nickoneill** [comment]
In this case it was suggested that house reps could still put pressure on the pick, even if they couldn't vote for it. We're thinking about ways to be more clear about why you're making a particular call.
