### ISSUE TITLE
add issue asking House Reps to back bill HR 804

### ISSUE THREAD

**Issue by lauren** [5calls/5calls#106]
This bill was just introduced to protect the National Security Council from partisan politics. Users can thank their rep for cosponsoring or ask their rep to cosponsor and support.

http://stephaniemurphy.house.gov/news/documentsingle.aspx?DocumentID=17
https://www.congress.gov/bill/115th-congress/house-bill/804/cosponsors?r=12
http://www.orlandoweekly.com/Blogs/archives/2017/02/01/stephanie-murphy-files-bill-that-would-remove-stephen-bannon-from-national-security-council

**Comment by nickoneill** [comment]
Thanks! Tracking this with the issues group
