### ISSUE TITLE
Dynamic call scripts

### ISSUE THREAD

**Issue by davemacdo** [5calls/5calls#107]
It would be useful to have the scripts replace the [Name] or [Zip] wildcards with the actual names and zips.

**Comment by zhoskins** [comment]
I think this has already been requested.... yup. [Issue 85](http://github.com/5calls/5calls/issues/85)

I would like to +1 this, though. It's incredibly helpful to have most of the script taken care of, and having less blanks to fill in when I'm talking to someone on the phone would make calls less stressful.

**Comment by nickoneill** [comment]
Yes, tracking in #85
