### ISSUE TITLE
Shorten call script

### ISSUE THREAD

**Issue by atenn** [5calls/5calls#108]
Suggest shortening the call script to be more concise and easier for staff to track, based on advice from a former senate staffer.

"Hi, my name is _______, I'm a constituent from **[CITY]**, zip code **[#####]**, I don't need a response. I **[support/am opposed to]** _______ and I encourage the **[Senator/Representative]** to please [support/oppose] as well. Thank you for taking my call!"

---------------------
Full post from the staffer for context (shared via the Pantsuit Nation Facebook group):

Friends! As some of you know, I used to work on Capitol Hill as the person in charge of all the incoming phone calls to my Senator's office.  I have some insider tips to make calling your reps easier and quicker.

1. Give your name, city, and zip code, and say "I don't need a response." That way, they can quickly confirm you are a constituent, and that they can tally you down without taking the time to input you into a response database.

2. PLEASE ONLY CALL YOUR OWN REPRESENTATIVES! Your tally will not be marked down unless you can rattle off a city and zip from the state, or are calling from an in-state area code.  I know you really want to give other reps a piece of your mind, but your call will be ignored unless you can provide a zip from their district.  And don't try to make this up; I could often tell who was lying very quickly thanks to the knowledge of the state's geography.  Exceptions to this are things like Paul Ryan's ACA poll which are national.

3. State the issue, state your position.  "I am opposed to ________."  "I am in favor of _______."  "I am opposed to banning the import of phalanges." I am in favor of a trade deal to lower the price of juice smoothies."  That's it.  That's all we write down so we can get a tally of who is in favor, who is against.  It doesn't matter WHY you hold that opinion.  The more people calling, the less detail they have time to write down. Help them out by being simple and direct.  This keeps calls shorter, allowing more callers through.

4. Please be nice! The people answering the phones on Capitol Hill already had the hardest job in DC and some of the lowest pay as well, and for a month now their jobs have become absolute murder, with nonstop calls for 9 hours every day.  Thank them for their hard work answering the phones, because without them our Senators could not represent us!

What does this sound like?

"Hi, my name is Mark, I'm a constituent from Seattle, zip code 98***, I don't need a response.  I am opposed to banning the sale of blueberries and I encourage the Senator to please oppose implementation of any such ban.  Thanks for your hard work answering the phones!"

This is how I wish every caller had phrased their message.  It makes it easier for the people answering the phones and takes less time and emotion than a long script.  I know that you want to say why, but keeping it short and sweet helps the office answer more calls per hour, meaning more people get heard.  The bigger the tally, the more powerful your voice.

Also, when you're reading off the same script as 100 other callers that day... well...they know what you're about to say, so you don't need to use the whole script for your opinion to be heard!

Pick one issue each day, use this format (I am in favor of _____ or I oppose ______), and call your 2 Senators and 1 Representative on their DC and State Office lines, and you'll be on your way to being heard.

![2017-02-02 10 37 48](https://cloud.githubusercontent.com/assets/25370878/22558637/022644c4-e934-11e6-8b70-a60c1f9e7141.png)
![screenshot_2017-02-02-10-29-08](https://cloud.githubusercontent.com/assets/25370878/22558635/0222ece8-e934-11e6-944c-e1f75aa03db5.png)
![screenshot_2017-02-02-10-29-23-1](https://cloud.githubusercontent.com/assets/25370878/22558636/0223ccc6-e934-11e6-8bea-65f69b2e9f07.png)

**Comment by oderby** [comment]
I suspect this is a point where reasonable people will disagree on what's best (similar to the single vs multiple issues per call, ie https://github.com/5calls/5calls/issues/24). To that end, even different staffers will have differing perspectives based on the individual senators they served, etc. 

I personally agree with this terse style, but I can also see benefits to longer style prompts. I think which to use also depends on the call volume and if your goal is to stay on the line for as long as possible (because you're the minority) or get your message heard quickly and get off so others can be heard. 

Perhaps this should just be a simple configuration/preference switch the user can choose?

**Comment by atenn** [comment]
There may be differing opinions on this.. and of course the scripts are always just a suggestion/way to get people started if they need it. In any case, I think covering the most important info first (location/no response needed/your stance) would be best to get the point across for data tracking purposes, as well as to further encourage calling by showing it doesn't have to be time consuming or thought out excessively.
Also considering the volume of calls federal offices are now receiving on a daily basis, I think it would be wise to encourage brevity.. 
Of course anyone can elaborate if they choose.. if people agree, perhaps a compromise could be a bullet list of reasons below the script for callers to pull from if they choose? Or a longer script below the short version as you suggest?

**Comment by nickoneill** [comment]
We've definitely shortened our call scripts recently, but we still say [Optional: add anything else here you'd like to say] in case of something special. I think we're good here.
