### ISSUE TITLE
Issue Text

### ISSUE THREAD

**Issue by joshfeingold** [5calls/5calls#111]
Suggest that for each issue text after issue we explain the actions the caller should do... Meaning that if they only need to call senate reps it is only two calls, but for those of us (like me) that don't understand things, I wonder why I'm not also calling my state reps.  Kind of a call to action final paragraph, where we tell the user what the specific next steps will be.

**Comment by nickoneill** [comment]
Info like this is wrapped up in a FAQ / script info page
