### ISSUE TITLE
Done Page

### ISSUE THREAD

**Issue by joshfeingold** [5calls/5calls#112]
After making their calls, the done page should allow for some/all of the following follow up actions, as appropriate to the issue:

Activism
1) Send email to all parties that we want user to send email to with the script we created.
2) Tweet to the rep/senator, etc, their position on issue x.
3) Post to facebook page of rep/senator their position on issue x.
3) Send a fax to same individuals via an online web to fax option.
4) For longer term issues, have a letter they can print out, sign, add a stamp, and put in the mail.
5) Link to white house petition site.

Publicize 5calls
In posts to twitter and facebook, link back to 5calls.

**Comment by nickoneill** [comment]
Starting to feel more complex here. We have sharing in there after you're done, I think that's as far as we want to go with it right now.
