### ISSUE TITLE
Privacy Link

### ISSUE THREAD

**Issue by joshfeingold** [5calls/5calls#113]
On chrome Version 55.0.2883.87 m (64-bit) on Windows 10, when I click the privacy link, the page content doesn't change.  The address bar shows the correct link to https://5calls.org/privacy.html, but for some reason no forwarding is happening.  Other two links in footer work as expected.  Odd issue, but I thought I would share it.

**Comment by zhoskins** [comment]
This is happening on my machine, as well.

Chrome Version 55.0.2883.95 (64-bit) on macOS Sierra Version 10.12.2

**Comment by nickoneill** [comment]
Interesting! I wonder if choo is doing funny things here because we're hijacking this for the rest of the pages. Will check it out.

**Comment by jonnaro** [comment]
Same issue. I would also add that once clicking on privacy, you can no longer click on any other issues -- so the site becomes unusable.

**Comment by nickoneill** [comment]
Fixed

**Comment by nickoneill** [comment]
Actually not fixed. Why does this work in development and never in production?
