### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by joshfeingold** [5calls/5calls#114]
Privacy page, references contacting us, but no contact information or email link is provided.  Suggest that we add a contact us link to send an email to the footer, and also use that for this location.   Alternatively, can have the user tweet to us with questions just to keep things simple for now since someone monitors the twitter account.

**Comment by charkattack** [comment]
Host the helpdesk: https://5calls.zendesk.com and link to Contact Us.

**Comment by joshfeingold** [comment]
Perfect. 

Perhaps link directly to: https://5calls.zendesk.com/hc/en-us/requests/new

**Comment by nickoneill** [comment]
Email link for now, I think the zendesk form looks a little too formal
