### ISSUE TITLE
Get Involved Page

### ISSUE THREAD

**Issue by joshfeingold** [5calls/5calls#115]
Suggest adding a get involved page to footer, if asking for donations, would be here. Also, could list specific sponsorship opportunities for known costs.  But more importantly, could have a place where we ask other developers, ui, testers, pr folks, and content writers to get involved in the appropriate place.  There is such a large group of people willing to get involved, I think grabbing them and putting them to work on specific teams should be pretty easy!

**Comment by nickoneill** [comment]
This sort of info should just live in a section on "About"
