### ISSUE TITLE
Subpages for subtopics?

### ISSUE THREAD

**Issue by adrn** [5calls/5calls#118]
First off: I love the site and the mission! Thanks so much for developing this.

A few of us have been interested in implementing something similar to provide scripts for general advocacy, but rather than recreate the wheel I thought I'd start discussion here to see if you would be interested.

One possibility is to build in the ability to add sub-pages with a set of call scripts for specific topics. For example (just off the top of my head):

- Science advocacy
- Environmental issues
- Women's rights

The main landing page could be what it is now (urgent or pressing issues), but the subpages could be for long-term advocacy. Our initial motivation was to create exactly this for science advocacy, as we're expecting that the [March for Science](https://marchforscience.com/) will activate a group of scientists that we want to be able to direct to a tool like this.

cc @chummels @lmwalkowicz

**Comment by nickoneill** [comment]
Thanks @adrn, we definitely want to provide tools for orgs / interest groups to make their own issues but I think it's a larger and more involved project than just this issue. If you'd like to be kept in the loop about this, just shoot me an email.
