### ISSUE TITLE
Adding representatives' public statements on an issue

### ISSUE THREAD

**Issue by kmjennison** [5calls/5calls#119]
Before calling a representative, I find myself Googling for public statements they've made on the issue (Twitter/Facebook posts, or press releases) so I can refer to the representative's view. It might be helpful if 5calls displayed their public statements on the call page.

We could probably achieve this programmatically by searching Twitter posts using the keywords of the issue, or scraping representatives' press release pages.

**Comment by nickoneill** [comment]
Hey @kmjennison, there are a few projects in the works that might be able to provide this data programmatically in the future. We're keeping tabs on them because this could be a really powerful addition to the call scripts. Thanks!

**Comment by kmjennison** [comment]
@nickoneill Great! What projects are you referring to? I'm interested in contributing something like this to 5calls if it's welcome.

**Comment by nickoneill** [comment]
Ugh, so many of these things fly by... I hardly can remember. I will post here if I see it again.

**Comment by nickoneill** [comment]
Tracking in #73
