### ISSUE TITLE
get local office numbers

### ISSUE THREAD

**Issue by jessehoff** [5calls/5calls#12]
Any easy way to provide local office numbers?

**Comment by jlev** [comment]
District offices aren't available via Google Civic, but some folks have assembled a list via Mechanical Turk. https://github.com/TheWalkers/congress-legislators/blob/4b5725df0b0c5db98810fedad3b98fa01b999ef3/legislators-district-offices.yaml

It might be a bit tough to join, since google doesn't provide the unique bioguide ID that most other open data sources use, but you could try parsing it from the photoUrl.

If you all want to discuss tech for good strategies and open data, there's a group of folks who do this professionally in a Facebook private group. I also have an open source call tool built on Twilio, if you want to automatically connect people with their representatives. https://github.com/spacedogxyz/call-power

**Comment by nickoneill** [comment]
Thanks @jlev, I'll check to see how we can join this data. We've started collecting some data ourselves but it's obviously a huge task.

Thanks for the group link as well! I'd love to participate

**Comment by malmckay** [comment]
Project VoteSmart has district office data. Not complete accurate, but well worth using - http://votesmart.org/share/api

I've done similar before and most of the work is having good heuristics for adding/removing numbers. Like maybe add a "wrong number" feedback option

**Comment by sageeprice** [comment]
In addition to this, would it be possible to add fax numbers? Many of these offices' mailboxes are filling up, so additional means of contact may be helpful.

**Comment by nickoneill** [comment]
Thanks @malmckay, I'm hesitant to use some of these other smaller data services as we're making *a lot* of requests and I know google has plenty of capacity to provide this.

I think the idea here is to develop a spreadsheet that we can easily update on gdocs, transform it into a sqlite database whenever there are updates and layer this information over top of the stuff we're getting back from google.

Because we do already get back a correct list of reps, we just need to add more phones (or modify phones) to that object.

**Comment by rednikki** [comment]
@nickoneill Let me know if you need a volunteer to manage that spreadsheet!

**Comment by flyingrat42** [comment]
I posted Issue #40 (under a different account) not realizing that this already existed.  I offered a spreadsheet with local numbers but it appears that that has been rolled into a new effort (http://thesixtyfive.org/), and their automated location matching likely uses the Google API as well, given that they seem to offer only the DC numbers.
If anybody wants to recreate the GDocs spreadsheet I'd be happy to help with that.

**Comment by reefdog** [comment]
Came here to request exactly this. DC voicemail boxes are filling up, but local numbers are still answering, so it'd be great to provide both. Happy to do what I can (collect numbers, build things) to help.

**Comment by chummels** [comment]
I wanted to add my name to the list of people willing to help on this front.  I have personally found I can *never* get through to Senators on their DC line, whereas I am able to reach them at various local phone lines, so I would think that adding local phone lines to 5calls would be extremely helpful.   I glanced over the repo and couldn't find the specific code responsible for pulling the contact phone numbers associated with different senators/congresspeople.  

I'm happy to just *look up* the numbers (100 senators, 435 congresspeople) and put it in a textfile or database somewhere, where it can be queried.  Obviously, it will need updating from time to time, particularly around new election cycles, but there shouldn't be too much churn so a static file should be OK for the time being.

Can someone point me to the code where it queries this information?  I can clone the repo and update it if people are OK with this.

**Comment by flyingrat42** [comment]
The Google spreadsheet I linked to in my comment of 6 days ago contains all of the local/district numbers.

**Comment by nickoneill** [comment]
Sorry about the wait here, we do have a few different sources of local numbers, the question is just how we integrate that into the data we already have. It's not a trivial task but we are making progress on it. More details as they become available and as we need help with finding / gathering data.

**Comment by chummels** [comment]
@flyingrat42 I looked at that, and it seems like a great resource, but it is somewhat incomplete.  For instance in California, Senators have 4 different local offices, and oftentimes, I am unable to reach them at the busiest (LA, SF), but I can get through at a few of the lesser ones (San Diego, Fresno).  Right now, the page you linked typically has only the DC office and one local office, so it would need to be updated to include all the district offices for each congressperson.  But as it stands, it is much better than just listing the DC number alone for each representative.

**Comment by chummels** [comment]
@nickoneill In looking at the code, I see you just use the google api to find representative information from civic info API.  Unfortunately, that information only contains the DC numbers for each representative.  As far as I can tell, there is no homogeneous and public facing location that stores all local/district information for each senator/representative. 

It seems that we could compile such a list locally, starting from the info that @flyingrat42 provides, and adding additional numbers manually.  The local list could be stored as a tab-delimited text file, or HDF5 file, or some other method, then queried after the representative's name is determined from the civic info API address search.  It all seems straightforward, but it seems unclear to me where we'd keep the local phone number source file.  In the repo?  In some other public-facing location?  Ideally, it might just be better to lobby the google API folks to include the district numbers in their content for each senator/representative, but I don't know how responsive they are.

**Comment by jlev** [comment]
@chummels district office contact numbers have already been compiled by people who use this data source professionally. It is all available in a flat yaml file at https://github.com/TheWalkers/congress-legislators/blob/4b5725df0b0c5db98810fedad3b98fa01b999ef3/legislators-district-offices.yaml, per my comment 8 days ago.

It is keyed by the congressional bioguide ID, which unfortunately Google Civic does not provide. So it will require a little bit of massaging to match responses between the systems, but I believe that is in process by @nickoneill

**Comment by chummels** [comment]
@jlev Sorry, I somehow missed that comment/data.  Thanks for the info, and glad to see you're on the right track.  Please let me know if I can assist in helping to code this up.

**Comment by joshfeingold** [comment]
Here are some local numbers that I found... surprised that this data isn't being captured by eff, tbh. http://www.theorator.com/government/house.html

**Comment by nickoneill** [comment]
That's the list we're currently playing with @jlev. We would provide our own service for 5 calls to start (replacing google civic for us entirely), possibly opening up the API to others later.

I've already had contact with the civic API team, they're not super fast getting data additions in and it doesn't sound like they're interested in including district offices or expanding in different directions that we're interested in such as #119 or town hall info.

I'll ping y'all specifically here when we need some help. We're going to take a first stab at what this looks like and then have people jump in once it's more well defined.

@joshfeingold that's for the 113th congress, so a bit out of date.

**Comment by beausmith** [comment]
Display local field office numbers: https://github.com/5calls/5calls/pull/137

**Comment by nickoneill** [comment]
All set here!
