### ISSUE TITLE
User Submitted: Edit Phone Numbers and Zip Codes

### ISSUE THREAD

**Issue by charkattack** [5calls/5calls#121]

**Comment by charkattack** [comment]
I live in Portland, OR (97211) and Jeff Merkley is one of my senators. Just a heads up that when I enter my zip or just Portland, OR the Eastern OR (Pendleton) number (tel:+1541-278-1129) comes up instead of the Portland number: (tel:(503) 326-3386).

**Comment by charkattack** [comment]
Just letting you know that this is still not fixed. Zip code 60035 gives no calls to make but 60015 does work.

**Comment by joshfeingold** [comment]
When the user clicks Unavailable, we should prompt the user for feedback such as this...

**Comment by josharian** [comment]
Thanks for finding a workaround and sorry for the trouble. There are problems with some zip codes that span districts.

**Comment by nickoneill** [comment]
Added this to a out of date info doc

**Comment by charkattack** [comment]
@josharian - sorry that wasn't directed at anyone in particular, just c&p a user's message
