### ISSUE TITLE
Unavailable Response Should Query For Why

### ISSUE THREAD

**Issue by joshfeingold** [5calls/5calls#122]
When the user clicks Unavailable, we should prompt the user for information regarding why things didn't work; perhaps prompt them with the most common reasons, voicemail full, call didn't connect, etc.  For certain categories autolog to zendesk as a content bug...

**Comment by jonnaro** [comment]
Too many actions/options might cause less engagement and be a risk to UI simplicity. 
Perhaps have a link for "bad phone number" but not sure what the other possibilities could be or how it would be actionable?

**Comment by nickoneill** [comment]
Yeah, I don't think we're going to get useful information out of this at the moment.
