### ISSUE TITLE
Add Senate Committee on Homeland Security to list of "Reject the Appointment of Steve Bannon to the National Security Council"

### ISSUE THREAD

**Issue by mrwweb** [5calls/5calls#125]
Received in an email from the Southern Poverty Law Center and seen also on Facebook:

> FIGHTING HATE // TEACHING TOLERANCE // SEEKING JUSTICE
> FEBRUARY 2, 2017
> 
> We just learned that the Senate Committee on Homeland Security is taking calls about Steve Bannon's appointment to the National Security Council (NSC).
> 
> We’re told that they’re tallying calls.
> 
> You might get a busy signal but try, try, try again all this weekend. Leave a message if you get through to voicemail.
> 
> The number: 202-224-4751
> 
> Be sure to tell the committee that you believe no individual whose primary responsibility is political in nature should be allowed on the NSC or authorized to attend its meetings. Partisan politics have no place in our national security.
> 
> Please also [email the committee using this form](http://donate.splcenter.org/page.redir?target=https%3a%2f%2fwww.hsgac.senate.gov%2fcontact&srcid=688105&srctid=1&erid=86829270&efndnum=12795650709&trid=151670ec-ae05-47f8-bdc5-ccd905ca21dd).

**Comment by nickoneill** [comment]
Thanks @mrwweb! I got this today too, we're working it up as an issue.
