### ISSUE TITLE
Add to JavaScript unit test coverage

### ISSUE THREAD

**Issue by cdoremus** [5calls/5calls#131]
I'm creating a number of unit tests for components including call, contact, done, issuesList, issuesListItem and script. They follow the pattern I used with callcount_test.js in PR #97.

**Comment by cdoremus** [comment]
Since the web site content is in flux, I am trying to not go overboard with test coverage, but making sure most of the bases are covered. Another complication is the nodes returned by choo's html tagged templates does not appear to implement a lot of the DOM API, and I thought it would be overkill at this point to use Karma or Mochify to run the tests in a browser. At any rate, FWIW, I feel they are a good starting point and will be useful when CI is added to the project.

**Comment by cdoremus** [comment]
Rob (@Mr0grog) as you suggested in #133, put together a PR configuring an in-browser testing solution of your choosing that runs off the Gulp test task and works with the callcount and localstorage tests you have in the branches you referenced in #133. When that is done, I'll migrate the tests in #134. Thanks, in advance.

**Comment by Mr0grog** [comment]
@cdoremus I was unable to get to this today, but will see what I can get done tomorrow evening (2/6).

**Comment by Mr0grog** [comment]
@cdoremus Sorry I’ve been so slow to get around to finishing this. I hope I haven’t held you up in any way. Preliminary PR is over at #181.

**Comment by Mr0grog** [comment]
Should this be closed, since #134 and #181 are done and merged? Any additional work this is meant to cover?

**Comment by cdoremus** [comment]
As @Mr0grog stated, work done on #134 and #181 implements this issue.
