### ISSUE TITLE
Cache and reserve rep images from our own domain for https

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#143]
Needed for ATS in iOS and mixed content security warnings in browsers

**Comment by josharian** [comment]
Started.

**Comment by josharian** [comment]
The dev airtable contacts db contains this photo url for John Barrasso (R-WY):

https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.congress.gov%2Fimg%2Fmember%2Fb001261_200.jpg&imgrefurl=https%3A%2F%2Fwww.congress.gov%2Fmember%2Fjohn-barrasso%2FB001261&docid=vZBGS9SwMnscEM&tbnid=F3kUFjIXNoAG-M%3A&vet=1&w=180&h=225&bih=776&biw=1415&q=john%20barrasso&ved=0ahUKEwjIkb2DgMjRAhVBqlQKHWYCAEsQMwg2KAUwBQ&iact=mrc&uact=8

This is not actually a photo url, it's some html served by google image. We need to fix this and check the prod contacts db for similar issues.

**Comment by nickoneill** [comment]
Yep, I fixed this in prod right now. I don't see any others. Those responsible have been sacked.

**Comment by nickoneill** [comment]
Do we care about serving these images with urls that contain stuff like dots and doublequotes? `ID-JamesE.Risch` or `ID-C.L."Butch"Otter`

**Comment by josharian** [comment]
I dunno. I originally used some hex goo, but it seemed worse. There is code in there that takes care that everything be url-safe. Happy to change it if you like--easy to strip out characters or simply obfuscate.

**Comment by nickoneill** [comment]
Added a full url in for clients and removed some other weird chars
