### ISSUE TITLE
Location Query doesn’t fire on about page

### ISSUE THREAD

**Issue by beausmith** [5calls/5calls#144]
## Repro Steps

1. Clear localStorage in browser
2. Go to <https://5calls.org/#about>

## Result 

You will see this "getting your location"

![image](https://cloud.githubusercontent.com/assets/28444/22621545/fc115da0-eada-11e6-9e39-7b2b3b1f5f66.png)

## Expected

Same behavior as homepage: geolocation with ipinfo.org fallback.

**Comment by capndesign** [comment]
This is working. Thanks @liamdanger!
