### ISSUE TITLE
BUG: contactIndex doesn't reset to 0 when switching issues

### ISSUE THREAD

**Issue by beausmith** [5calls/5calls#166]
## Repro
1. go to any issue with multiple contacts.
2. press a button for one contact.
3. switch to another issue.

## Result
You are not on the first contact for the issue you just switched to.

**Comment by bernardwang** [comment]
I took a quick look, and I think resetting `contactIndex` when switching would mean you would lose "progress" on any uncompleted issues. While that is better than what it is currently doing, it seems like the best solution would be better to replace `contactIndex` with an array of indices for each issue. 

I'm new to this project, but would anyone mind if I tackled it?

**Comment by nickoneill** [comment]
If contact position is maintained between issues right now, it's entirely unintentional. By all means check it out @bernardwang!
