### ISSUE TITLE
Remove House Reps from Supreme Court call, since they do not have a role in confirmation

### ISSUE THREAD

**Issue by ms** [5calls/5calls#173]
Unless I am mistaken, House Representatives do not have a role in Judge Gorsuch's confirmation. I think it would make sense not to include calling them for that issue so that the messages they receive are focused on issues they can affect.

This might arguably be the case for other nominations (Senate only) or to initiate impeachments (House only).

**Comment by nickoneill** [comment]
Many of our issues have a clear action that your rep should do or *not* do; voting for a confirmation or not voting on a particular bill for example. In this case we're currently focused on putting up some general opposition for the supreme court pick so we decided to direct the issue towards both houses. Good call though!
