### ISSUE TITLE
Feature request: Undecideds list

### ISSUE THREAD

**Issue by gregerhardt** [5calls/5calls#177]
I use and love your site, but the zip-code search is limiting.  It would be great to have alternative search features.  Specifically, a list of undecided senators or representatives on a particular issue.  Another option may be to have search such as a list of all senate democrats, or all representatives from swing districts.  

Thanks for your hard work!

**Comment by nickoneill** [comment]
Hi @gregerhardt. It's important that you call your own reps only, the other congresspeople generally don't care about your opinion if you're not a constituent. That's why we focus on your location so heavily.
