### ISSUE TITLE
Golang side of codebase doesn't run locally after clone

### ISSUE THREAD

**Issue by rreed** [5calls/5calls#18]
It's me again. :P

There are a few things needed to do this that I fixed, then one that I couldn't, per the docs, so I'm filing this since presumably it's just permissions-related.

First, `go run *.go` won't work without getting all of the libraries first. I just did `go get foo` for each library, but maybe there's a better way; I'm not much of a Go developer. :)

Secondly, you still need keys; I did `env AIRTABLE_API_KEY=foo env CIVIC_API_KEY=bar go run *.go` but there's also probably a better way to do this.

After both of these, it starts but errors out on the `ListRecords` call (`airtable.go:108`).

`2017/01/25 19:48:58 unable to load contacts, NOT_AUTHORIZED: You are not authorized to perform this operation [HTTP code 403]
exit status 1`

The first two are just missing documentation, but the third one has me a bit puzzled. :)

**Comment by nickoneill** [comment]
Are you planning on improving the backend? If not (or not right now at least) you can just run the frontend and connect to the prod backend at 5calls.org - that works fine!

I still have to write up something quick about how to set up dev airtable. I'll get to that very soon.

**Comment by dektar** [comment]
I've run into the same issue, I was hoping to use a local backend so as not to impact the real counts.

Do you mind some extra POSTs to the prod backend? And/or is there a "testing" flag we can pass along to the prod backend so it doesn't get counted, but still returns the right responses?

**Comment by nickoneill** [comment]
I just sent you an invite to our dev airtable @dektar - but don't worry about it if you pass a couple extra results to the prod backend.

**Comment by ejlangev** [comment]
@nickoneill Ran into the same issues, thought it would be nice to have full info on how to get the backend running for dev.  I pinged you in the ProgCode slack channel you set up, was thinking I could complete some docs as a first PR.

**Comment by nickoneill** [comment]
@ejlangev sent you some notes on slack, I'd love to get some better docs for setup!

**Comment by ejlangev** [comment]
@nickoneill I think this issue should be resolved now.  Good to close?

**Comment by nickoneill** [comment]
Yep, looks great now
