### ISSUE TITLE
Link to town halls

### ISSUE THREAD

**Issue by remoun** [5calls/5calls#180]
Link to (or better yet, embed) info about upcoming town halls, by location.

For example, the [Town Hall Project](https://twitter.com/townhallproject) has compiled a [spreadsheet](https://docs.google.com/spreadsheets/d/1yq1NT9DZ2z3B8ixhid894e77u9rN5XIgOwWtTW72IYA/htmlview?sle=true#gid=1473996386)

**Comment by nickoneill** [comment]
Thanks @remoun, we're working on this.

**Comment by nickoneill** [comment]
Fixed in #286
