### ISSUE TITLE
"set your location" or "add an address" prompts should clear and focus the input

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#185]
Some feedback with confusion on these items. Clearing the input lets people see the placeholder where it says "address or zip"

**Comment by capndesign** [comment]
@nickoneill Could you clarify exactly what you want to see? In Chrome and Safari, the address field input is focused for me. Are you trying to say that you want to see the placeholder?

**Comment by nickoneill** [comment]
We're getting feedback that says "there's no place to put in an address, I only see the zip field". My suggestion for a fix was to remove the existing stuff in the field so the placeholder ("enter a zip or address") was more prominent. Open to anything that clarifies the situation.
