### ISSUE TITLE
Set up continuous integration testing

### ISSUE THREAD

**Issue by Mr0grog** [5calls/5calls#188]
As a follow-on to #181 and #131, I’m going to work on configuration for multi-browser testing via Sauce Labs or Browserstack (TBD by @nickoneill) and CircleCI to run them automatically for all pushes and PRs. (Someone with actual repo permissions here will need to actually create a CircleCI account and link this repo, though.)

**Comment by oderby** [comment]
@Mr0grog regarding #161, all I can say is that I reproduced and subsequently fixed the issue while testing on Windows 7 IE 11. I do not know if it reproduced on Windows 8 or 10.

**Comment by cdoremus** [comment]
+1 Thanks for helping out with this.

**Comment by Mr0grog** [comment]
@oderby, ok, thanks. I’ll take a quick look-see at it to try and tell. Maybe the right thing is to just have IE 8 & 11 (since those are the most common two) on Windows 7, 8, and 10. It’ll be a lot, but hopefully not too big a deal if running in CI.

**Comment by nickoneill** [comment]
@Mr0grog can you tell me what you need here? I don't know what would serve us better between browserstack or saucelabs - shoot me an email, it's on my github profile. I added circleCI, still waiting for that to complete a build.

**Comment by Mr0grog** [comment]
@nickoneill If you don’t have strong feelings about Sauce vs. Browserstack, let’s just go with Sauce. I’ve used both manually, but am more familiar with automating Sauce. I don’t feel like there’s any especially meaningful difference.

I will try and get a PR for this together on Wednesday. Then we can poke at Circle until we see it run the tests.

**Comment by cdoremus** [comment]
Having never worked with Sauce Labs (or Browserstack), I took a look at their docs this evening. Rob (@Mr0grog), please correct me if I am wrong, but it appears that we will be using Sauce Labs to run Selenium Webdriver end-to-end integration tests. If that is correct, we need to start creating these tests. I suggest that we create a top level folder to hold these tests (name it e2e-tests??). An alternative idea is to create a separate 5calls project to hold the e2e tests. We also need to make a decision as to what language (or Webdriver API) to use in coding these tests. I suggest that we use the JavaScript/Node API. 

Please comment (Rob or anyone else).

**Comment by Mr0grog** [comment]
@cdoremus Both Sauce and Browserstack are basically just fancy webdriver targets. BUT! There are Karma plugins for both Sauce Labs and Browserstack that will allow you to run your normal Karma tests via webdriver and collect the results, so you can do unit tests (not just integration tests). That’s what [the configuration I mentioned on #181](https://github.com/Mr0grog/5calls/compare/tests-with-karma...Mr0grog:tests-with-karma-ci) is using.

You can _also_ run integration tests on Sauce Labs and Browserstack. You can run them locally using webdriver, too. Integration tests would be _great_ to have, but I think they are orthogonal to getting up and running on Sauce or Browserstack. That should be a different issue + PR, and we should have more discussion there.

**Comment by nickoneill** [comment]
I just dug around on saucelabs and I don't see anywhere that I can set up a github project to build tests (manually or automatically). A little help here?

**Comment by oderby** [comment]
Nick, did you try just signing up for an Open Sauce plan here?
https://saucelabs.com/beta/signup/OSS/None

**Comment by nickoneill** [comment]
I did - do I have to go through the "sauce connect proxy" setup? It should be free for open source projects so anyone feel free to set one up and tell me if they need github collaborator access.

**Comment by Mr0grog** [comment]
Hey all, I tried to post clear setup instructions over on the PR: #193

**Comment by oderby** [comment]
@Mr0grog awesome! I believe I successfully created a saucelabs account for 5calls and sent @nickoneill an invite. Will coordinate with him over slack to make sure he has credentials and gets everything setup.
