### ISSUE TITLE
Minor improvements to the Issue pages

### ISSUE THREAD

**Issue by shellen** [5calls/5calls#19]
1. Consider an even darker CSS overlay of that image, a lot of contrast issues for differently abled folks
2. Ask for my name when I select the first issue to call for and insert my name into the script. Since the goal is to make this painless, help out flustered callers. City, State too if possible.
3. Insert the selected elected officials name in the Script 'May I ask how CHUCK GRASSLEY' will be...'
4. Add a +1 in front of numbers, calling from a landline, you still need the stupid 1.

**Comment by kimflournoy** [comment]
Definitely +1 on the "put my name into the script" - I end up copying and pasting into a separate document and doing this manually.

**Comment by jameshome** [comment]
1 and 4 were fixed with the new design. 2 and 3 are being discussed in more detail in #85. Closing this one out.
