### ISSUE TITLE
Auto form-fill for free fax service

### ISSUE THREAD

**Issue by lorainekv** [5calls/5calls#191]
Since my rep's voicemail was full, I wanna work on a button that will autofill the receiver info fields and insert the call script into the fax body for a service like https://faxzero.com/. Generally, to make it convenient to fax from a mobile device.

**Comment by lorainekv** [comment]
Looks like [FaxZero's TOS](https://faxzero.com/terms_of_use.php) requires written permission for automated access to the website. Lmk if this is something folks are interested in exploring, and I'd be happy to contact them.

**Comment by nickoneill** [comment]
Hey @lorainekv, while I understand that some people are finding it useful to fall back to faxes if phones are unavailable, our platform serves people best when we do one thing well. For the moment, that one thing is phone calls.
