### ISSUE TITLE
Track call statistics locally

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#195]
I think keeping a running tally of how many calls a user has made is a good start for getting people to come back more frequently because they can start to see the impact they've made over time.

To accomplish this, we should track the number of calls made, who they're made to and what issue id they're made for. For now, we should just surface the total number of calls made.

Localstorage is probably the best way to accomplish this at the moment. We can always migrate to server stats in the future.

Before deployment, we should have #52 fixed so people don't loose that data.

**Comment by schraj** [comment]
@nickoneill Do you know if anyone is working on this one?  If not, I will.

**Comment by nickoneill** [comment]
This is wrapped up in #229
