### ISSUE TITLE
Refactor main.js into namespaced models; add tests for effects/reducers

### ISSUE THREAD

**Issue by oderby** [5calls/5calls#206]
As per discussion in #190, we should be able to add unit tests for effects and reducers. Before we can do this, I think it would make sense to break apart the monolithic model in main.js. I think we can do this simply by creating 2 namespaced models, `issues` and `address` (to avoid confusion with the special `location` namespace choo provides for interacting with the `window.location` object), and then just keep a barebones set of initialization logic in the top level model. 

Once that is done, we can start filling in unit tests for our reducers and effects.

**Comment by nickoneill** [comment]
I know this exists in choo but I hadn't yet wrapped my head around how to do it, happy to entertain anything that starts to simplify our gigantic main.js

**Comment by cdoremus** [comment]
I was going to propose that we split state, reducers and effects into their own modules (source files) to improve testability and reduce complexity. Thoughts?

**Comment by oderby** [comment]
In my head, I was envisioning we'd have 1 file per model, which held all state, reducers and effects for that model. I'd imagine we could structure each module such that the model parts are all accessible for testing. Putting everything related to a model in one place makes it much easier to reason about and understand.

@cdoremus how is this different/similar to what you're proposing?

**Comment by cdoremus** [comment]
Owen (@oderby), I agree with your thinking. But I thought some more about it and took a look at ```models.go``` and ```main.js``` and think that a ```contact``` model should be added to the mix.

I'm sorry, but I was confused by your term "namedspaced models". I assume that they are the same as ES6 or Node modules.

**Comment by greggraf** [comment]
I am exploring writing unit tests for `startup()`  which is currently defined in `main.js`.

To  help expose `startup()` for unit testing (and as an incremental step towards refactoring main.js) I would like to propose the following:

- create a file called `./static/js/app.js` (or `application.js` or `5calls.js`)
- move `appURL` constant into this file 
- move all lines of code that interact with `localstorage` to set initial `state` into this file
- this file will be a module that exports two properties: `model`, `routes`
    - `model` will be the object currently passed to `app.model()` in `main.js`
    - `routes` will be the array passed as the second argument to `app.router()
- `require` this file in at the top of `main.js`
- use the exposed properties as arguments to `app.model()` and `app.router()`

This seems pretty safe as it is re-arranging code, not changing the code much. Any issues with variable scope will be pretty quickly exposed as JS errors. 

This module can then be used for unit testing of difficult to reach code in `main.js.`

Exposing `routes` may be feature creep. I thought it could be useful for automated processes that might want to know what routes are legit and testing that the app responds to them.

**Comment by nickoneill** [comment]
Can we hold off on this until we get some more clarity on #260? I don't want to waste anyone's time here without knowing the timeline on getting away from choo v4.

**Comment by nickoneill** [comment]
This is resolved now that we're moving to react, no more monolithic main.js
