### ISSUE TITLE
Calling Non-secure 5calls.org throws error

### ISSUE THREAD

**Issue by webRat** [5calls/5calls#210]
* http://5calls.org throws an error
* doesn't redirect to https://5calls.org

**Comment by nickoneill** [comment]
I couldn't reproduce this - was this just around 7:30 this morning when we were down for a few minutes?

**Comment by webRat** [comment]
@nickoneill - No, it's happening right now?
![non-https-call](https://cloud.githubusercontent.com/assets/59866/23181346/a6cc5e42-f842-11e6-9324-51c77707540a.png)

**Comment by nickoneill** [comment]
How about now?

**Comment by webRat** [comment]
@nickoneill both 5calls.org and www.5calls.org is redirecting to https://5calls.org now.

I'd point out that secure/non-secure calls www.5calls.org needs to redirect to https://5calls.org instead, but at least it's working.

Thank you.

**Comment by nickoneill** [comment]
Thanks for checking, the http -> https redirection seems like it happens automatically in chrome for me. I'll fix the http+www issue too.

**Comment by webRat** [comment]
@nickoneill Probably not important, maybe for SEO, but... your call. ¯\_(ツ)_/¯

**Comment by nickoneill** [comment]
Totally important, thanks for bringing it up :)

**Comment by nickoneill** [comment]
OK, last issue is just www -> non-www which is tracked in #52
