### ISSUE TITLE
Allow users to see inactive issues

### ISSUE THREAD

**Issue by oderby** [5calls/5calls#215]
## Motivations
We've gotten many emails asking to be able to view old issues. These emails usually fall into one of two categories
1. **Continue Calling** Sometimes, users disagree with us on issue priority, and want to continue making calls about something we've bumped off the front page.
2. **Disappearing Issues** Users share an issue on social media, but by the time their friends click on it, the issue is inactive, and so they hit a confusing dead end.

## Proposal
We propose the following changes:

1. Add a new issues page. This page will keep the same chrome as all other pages, and keep the current list of active issues on the left. But the main content area will start with a brief copy blurb explaining about the page and old issues, and encouraging people to call about the active issues on the left. It will then have a list of all previous issues. To start, this list will include the issue title, and perhaps the number of contacts for the issue (exact layout TBD by @beausmith). When a user clicks on any of the old issues in the list, they will be taken to that issue page. 
2. Add a link to the new issues page at the bottom of the active issues list with text "view old issues".
3. Add support for a new query param, 'inactive', to the backend `GET /issues` query handler. Passing just 'inactive' or 'inactive=true' will return only inactive issues. Passing 'inactive=false' will return only active issues. Omitting the 'inactive' param will also return only active issues, to preserve backwards-compatibility with existing clients.
4. Support for displaying inactive issues at the usual issues route. If the issue is inactive, the page will have a disclaimer banner/bar at the top, explaining this is an inactive issue and we are no longer encouraging folks to call about it. Otherwise, the page will look identical to any active issue. This means users can report statistics for inactive issues.

## Deferred Thoughts/Questions/Ideas
* What is the ideal/desired lifecycle for an issue? For this first version, we are keeping it simple and in line with the current schema, where an issue is either active or inactive, and can toggle between the two states as needed. But I can imagine a slightly more complex state machine for managing issues, where some issues go dormant for a while until they become relevant again, while other issues are resolved (e.g. Cabinet nominee gets confirmed, law is passed and enacted).
* Do we ever imagine limiting the number of issues on the front page such that we will have more "active" (i.e. important) issues to call about than we show on the front page?
* Pagination. For now, we're hoping the page will handle 50-100 issues. But we'll soon outgrow that, and both the api response and page UX will become too unwieldy.
* If we want to expose call stats per issue, the old issues page could be a good place to do it
* We may want to start capturing information when we de-activate an issue, such as reason, result, timestamp, etc.

**Comment by oderby** [comment]
@nickoneill feel free to supply a better/more correct description of the use cases/motivations if you'd like.

**Comment by beausmith** [comment]
@oderby - Thanks for capturing this.

**Comment by nickoneill** [comment]
Great writeup, I think this makes the big points. One distinction is between issues that are genuinely not relevant (vote no on sessions) which we should remove and *not* let people call about, and inactive issues which simply aren't on the front page and people can reach and call as much as they want. I don't think we need any disclaimer in that case.

Another option for API integration is: linking to an issue page that is not currently active (on the front page) can request info from just that issue from the backend ("give me details about issue number 1234"). Then a list of inactive issues can just be a long list of IDs so we don't have to send them all every time.

**Comment by oderby** [comment]
That's a good point. In this proposal, we are keeping it simple and ignoring that distinction. This way we don't need to migrate the Airtable Base and can get this out quickly. This does mean that users would be able to log calls for irrelevant issues. Is that not acceptable?

Re API - yeah, that was the alternative. I was thinking we'd keep this simple to get the feature out quickly and then optimize/improve later. Concretely, just returning all inactive issues is 100KB and takes <500ms. That's obviously going to get worse over time, but I think we would have some time to propose and negotiate a more robust api for serving issues.

**Comment by nickoneill** [comment]
Some quick points that @oderby and I chatted about this afternoon:

* certain issues need to be marked dead, no one should ever see a call about calling for the nomination of jeff sessions even if they find a link to it.
* We can keep these in the db so we can reference their issue ids, just add a new "dead" column and then all views can filter these out
* all non-frontpage issues on another pages is 👌 
* we don't need to call out issues for why they are or aren't on the front page, people are on that page because they care about the issue, no need to diminish that

**Comment by schraj** [comment]
I would take on the UI implementation for this if no one else has started on it.

**Comment by nickoneill** [comment]
This is started in #220 @schraj, send me an email and I'll invite you to the slack
