### ISSUE TITLE
Pressing back button breaks the app

### ISSUE THREAD

**Issue by oderby** [5calls/5calls#216]
# Repro Steps
1. Go to [5calls.org](5calls.org)
2. click on first issue (should get to url such as `https://5calls.org/#issue/recmbgLuYnXWoJhQq`)
3. click browser back button
# Result
URL is updated to malformed url (e.g. `https://5calls.org/#issuerecmbgLuYnXWoJhQq"`) and get a stack trace in the console:
![image](https://cloud.githubusercontent.com/assets/1351158/23252661/7d5aa558-f966-11e6-8e76-e0c7b4827ca5.png)
Clicking on any further links has no effect. 
Reloading page also results in same error and broken app state.
# Expected
It should navigate back to home page (or whatever page user was previously on)
# Environment
Chrome 55 and Firefox 51
# Notes
This is really two bugs
1. Broken history
2. unmatched routes throw an uncaught error, crashing the entire app. This may be something we should report upstream to [choo](https://github.com/yoshuawuyts/choo), but should definitely see if we can't handle locally.

**Comment by nickoneill** [comment]
FYI this previously worked OK, not sure what broke it but it's very particular.

**Comment by sshevlyagin** [comment]
Tried to repro. Looks like it's no longer an issue.

**Comment by nickoneill** [comment]
Yep, all set here. Thanks for the reminder @sshevlyagin!
