### ISSUE TITLE
iOS Safari - Links to "About" and "Why Calls Work" buggy 

### ISSUE THREAD

**Issue by jzlandau** [5calls/5calls#22]
In Safari for iOS 10.2.1, the links to "About" and "Why Calls Work" pages do not work, unless one holds the click, and selects the option to open in a new tab.  Given the importance of being transparent about who runs this project, I would love to see this fixed.

**Comment by nickoneill** [comment]
I don't see this behavior on my own Safari - can you pop the debug console open and see if it's complaining about anything else @jzlandau?

**Comment by jzlandau** [comment]
Very weird.  I noticed this behavior repeatedly earlier today, but it seems to have "fixed itself".  Apologies!
