### ISSUE TITLE
Clean API for requesting JSON data for native app?

### ISSUE THREAD

**Issue by dexterlohnes** [5calls/5calls#23]
I'm interested in developing a native app interface for this project. Is there a documented API I can reference for getting JSON responses for my own front end, or do I need to wade through the source to find out what's happening?

Thanks!

**Comment by nickoneill** [comment]
I would suggest watching the network requests to 5calls.org in your browser when you load the 5calls page, it's a pretty straightforward API but I don't have a ton of time to document it right now.

Please update here with your status if you make progress!

**Comment by jadametz** [comment]
Unless there are other endpoints hiding elsewhere in the code, it looks like everything is well defined [here](https://github.com/5calls/5calls/blob/master/go/main.go#L95-L106).

If no one else is working on this, I was going to get started documenting the API in [Swagger](http://swagger.io/)...

**Comment by jadametz** [comment]
GitHub won't let me upload the yaml directly (as it's an unsupported file type). I created a Gist of the spec instead: https://gist.github.com/jadametz/f53d4a0cd304937748d22ade38d37f77

You can see how this would look as interactive documentation by heading over to http://editor.swagger.io/#/ and pasting the yaml into the editor.

With that done, you could host the documentation on the 5calls.org site and/or potentially speed up development for others by generating client libraries..

![](https://d3vv6lp55qjaqc.cloudfront.net/items/343S023P1x372a3t0v3E/Image%202017-01-29%20at%206.42.02%20PM.png?X-CloudApp-Visitor-Id=322658aa84370effc0bba45f39d404ea&v=1b5aef1f)

Thoughts?
