### ISSUE TITLE
FAQ pages need a working home button to get back to 5calls.org

### ISSUE THREAD

**Issue by cdoremus** [5calls/5calls#234]
In working on e2e tests, I created a test that clicks on the FAQ page link on the ```5calls``` home page, which redirects to a ```5calls.zendesk.com``` URL containing a number of FAQ pages. The ```5calls``` icon on the top of the ```5calls``` zendesk site points to what looks like a ```5calls``` zendesk home page. It should point back to https://5calls.org.

Also, I'm not sure what can be done about branding ```5calls.zendesk.com,``` but we should try to make the pages look more like they integrate into ```5calls.org.```

**Comment by nickoneill** [comment]
Thanks for making note of this, I'll see what we can do on the zendesk side of things

**Comment by cdoremus** [comment]
@nickoneill I noticed that that zendesk has an API. It would be nice to use it for the web site to be able to integrate the FAQ content into our look-and-feel. Android and iOS could also use API calls to get this content. Is this something that I should look into?

**Comment by cdoremus** [comment]
The zendesk page was replaced with a real FAQ page in #285 so this issue is no longer valid
