### ISSUE TITLE
Explain 1 issue per call in FAQ

### ISSUE THREAD

**Issue by Ipstenu** [5calls/5calls#24]
It seems ineffective to call the same person X times about issues. It will fill up mailboxes faster, which is already a problem. Perhaps allowing to sort by contact person could help this.

(PS, thank you for this work! The scripts help anyone with anxiety know what to do!)

**Comment by nickoneill** [comment]
Thanks @Ipstenu! It's more effective right now (according to staffers) to provide a single issue per phone call / voicemail. Hopefully the local offices support in #12 will alleviate this for the moment.

**Comment by Ipstenu** [comment]
That makes sense and sounds like a FAQ page may need this information :)

**Comment by nickoneill** [comment]
You're totally right. Let's keep this as a reminder.

**Comment by oderby** [comment]
Please include a reference/source in your explanation. It goes against my intuition and much of the (equally source-less) advice I currently see swirling around in my social circles (so as a user, I'm skeptical right now of using the site as is).

**Comment by nickoneill** [comment]
Hi @oderby, we're in contact with senate staffers who are actually in charge of answering the phone so that's where we're getting this info right now. Will update you if we hear that anything changes.

**Comment by nickoneill** [comment]
This is covered in the FAQ
