### ISSUE TITLE
Create additional E2E tests

### ISSUE THREAD

**Issue by cdoremus** [5calls/5calls#246]
I am proposing additional end-to-end (E2E) tests to aid our development and refactoring efforts. I will concentrate on the major ```5calls.org``` use cases.

Comments and suggestions are welcome.

The E2E tests will make use of the [Page Object Pattern](http://www.seleniumhq.org/docs/06_test_design_considerations.jsp#page-object-design-pattern) to help separate page-specific code from test code to buffer against test fragility when page content changes.

As a start, these use cases will be tested (with test cases listed below each):

1. Display home page 
a. After browsing to home page, assert that page has been rendered

2. Display Issue detail page
a. After an issue has been clicked in the sidebar, assert that the issue details page is rendered.

3. Display More Issues page 
a. After 'view more issues' linked has been clicked, assert that More Issues page is rendered.

4. Lookup Address
a. Click on the address link to render the address input text box (if it is not already rendered). Enter a zip code into the text box and click Go. Check that the same zip code is now rendered as the address link.

5. Display About page
a. After About link is clicked, assert that user navigates to About page

6. Display FAQ page
a. After FAQ link is clicked, assert that user navigates to FAQ page

These additional test cases will be deferred to another PR (or PRs) once a PR based on the above use cases have been merged into master:
2.b. After clicking a call result button (Unavailable, Made Contact, etc.)  on issue details page, assert that the number of calls decrements or the '1 more person to call for this issue' message no longer renders because all calls have been made.
3.b. Assert that any completed (green checked) More Issue maintains checked state after the More Issue page closes and is subsequently re-rendered.
3.c. Make sure that clicking on 'view more issues' maintains the state of which contacts were clicked for a particular issue

**Comment by cdoremus** [comment]
Making progress and got the tests working using http://localhost:8000 as the base Url. Should that Url also work in CircleCI/Sauce Labs or should I configure the e2e tests to run using a different Url in CI?

**Comment by nickoneill** [comment]
I'm not sure? Who would be best to ask here, @Mr0grog?

**Comment by greggraf** [comment]
I found this:
  https://circleci.com/docs/1.0/browser-testing-with-sauce-labs/

Which indicates http://localhost:8000 could work.

I even took a pass at adapting that sample code to what I think would work for this project (temporarily replacing the existing test command):
   https://github.com/greggraf/5calls/blob/test-e2e-on-saucelabs/circle.yml

Unless someone else has definitive experience or opinions,  my next step might be to try to create a test CircleCI/SauceLabs setup to test this out against .

**Comment by nickoneill** [comment]
I gave @cdoremus access to our existing setups to see if he can work some magic here. Let me know if you need any additional support.

**Comment by Mr0grog** [comment]
Hmmmm, @greggraf does the way you’re running sauce connect in that circle config still work with the unit tests? The general setup seems reasonable, but I wonder if the two sauce connect tunnels would conflict (the unit tests also spin up their own sauce connect process).

You should be able to tell the Karma Sauce plugin not to start its own sauce connect instance by setting `startConnect: false` in the config file here: https://github.com/5calls/5calls/blob/master/karma.ci.conf.js#L103-L105
Then just make sure you don’t shut down sauce connect until the unit tests have finished.

I don’t know that it’s necessary, but you might be able to simplify the circle config by managing sauce connect using the [sauce-connect-launcher package](https://www.npmjs.com/package/sauce-connect-launcher), which will autoinstall sauce connect if not present and give you a nice callback when everything is up and running. This is the same package that the karma sauce plugin uses. Might be more work than it’s worth at this point if you’ve already got it working well, though.

**Comment by greggraf** [comment]
@Mr0grog this information is awesome. It would be great to try to use the sauce-connect-launcher package for both use cases.

To clarify: I have not run the config so I don't know if it works. I had found sample code that was doing something similar and put together a quick guess at how it might be applied to this case. 

My guess replaces the existing circle config. I planned to prove out the approach first, then roll the unit tests back in.

I stalled because I didn't want to test/develop/debug it on the existing CircleCI and SauceLabs instances. From @nickoneill's comment above it seems that @cdoremus might be trying something.

**Comment by cdoremus** [comment]
@greggraf right now, I'm focused on getting the e2e tests right and moving #252 forward, not the CI configuration. I want to use the tests to guide the refactoring of `main.js` as @oderby proposed in #206. That file is too big and complex and not unit testable, and it's getting worse with each new feature we add to the app. 

I do want the CI integration to happen and if you are interested in working on that, be my guest. I was hoping that @Mr0grog would help since he set up the original CI configuration, but I know his time to devote to this project is limited.

**Comment by cdoremus** [comment]
PR #252 has been merged into master and issue #291 has been created to integrate this work into our CI pipeline.
