### ISSUE TITLE
Scrolling does not occur when activating an issue from the About or Done page

### ISSUE THREAD

**Issue by bernardwang** [5calls/5calls#247]
Scrolling an issue into view uses the `#content` selector, which does not exist in `aboutView.js` or `doneView.js`. It looks like it is just trying to scroll to an element that doesn't exist in the view yet. 

I don't know for sure, but on initial inspection I don't think it was introduced by [#208](https://github.com/5calls/5calls/issues/208). 

[About Page](https://i.gyazo.com/e09ff294dbe3322f99020db920438167.mp4)
[Done Page](https://i.gyazo.com/abfe0557dc4a5d7a7c75eccdde77d278.mp4)

**Comment by cdoremus** [comment]
Fixed with PR #250 that has been merged into master.
