### ISSUE TITLE
support specific ordering of callees (Reps first vs Senators first etc) 

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#257]
in some situations, we want the callers to call both their Reps and their Senators--for example, when a piece of legislation is being voted on soon in the House but is also going to the Senate shortly.  however, if the Senator appears first in the call list, it confuses engaged users who know the legislation in question is currently in the House. in this situation, we would like to be able to specify that the caller call their Rep first and then also their Senator. 

it would likely be optimal to implement this in a way that allows the poster of the issue to select explicitly the order in which all the potential callees are shown to the caller, since this might apply to other sets of callees beyond Reps/Senators etc.

**Comment by oderby** [comment]
Interesting - this actually sounds like separating between "required" and "optional" calls. e.g. for the example you gave, Rep is required but Senators is "optional". @piebob thoughts?

Regardless, I think this is a good point - we should just honor the order in which the contacts are listed in the `Contact` field in the Airtable base. I believe that Airtable treats linked record fields with multiple links as ordered (can't find it explicitly in the documentation, but is implied in several spots and they discuss [reordering links](https://support.airtable.com/hc/en-us/articles/217521267-Reordering-record-links)). However, I can confirm that the order is not reflected in the JSON payload for issues sent to the frontend, so I suspect this is unordering/reordering is occurring in the backend. Most likely in the JSON marshalling.

**Comment by oderby** [comment]
Hmm, just dug in a bit and it appears to be an issue with the Airtable API not preserving the ordering of the contacts. I've sent an email to them on the issue, will see what their response is.

**Comment by oderby** [comment]
Okay, heard back from Airtable - they return the links in **reverse** order. So should be easy enough to fix.
