### ISSUE TITLE
Mixed content warning when an issue is selected

### ISSUE THREAD

**Issue by mryand** [5calls/5calls#26]
The site presents a secure "lock" icon in Firefox upon initial load, but once an issue is selected the security display changes to a mixed content warning: "Connection is not Secure".

The warning may cause concern for users.

This appears to be because the senator/rep images are served via http rather than https.

Perhaps the images could be fetched & cached server-side and delivered via https? This also would allay any image-scraping concerns.

**Comment by norcross** [comment]
Do you have a particular issue / person this comes up on so we can test against it?

**Comment by nickoneill** [comment]
@norcross you have access to the airtable, yeah? Some contacts in there definitely have http images (whoops), we should totally be caching that locally to not piss off whoever we linked the image from :P

**Comment by norcross** [comment]
good call

**Comment by nickoneill** [comment]
Should be fixed with #143
