### ISSUE TITLE
Send `via` parameter with call report

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#261]
This is to identify the client when we report call stats. Should be `web` for the web client.

**Comment by oderby** [comment]
And probably should be `test` whenever not run in production environment, right?

**Comment by nickoneill** [comment]
Yes! @dektar just mentioned this on slack and it's an excellent idea.

**Comment by schraj** [comment]
I'll do this unless someone else is.

**Comment by schraj** [comment]
Is "running in the production environment" solely determined by the "debug" flag from localstorage (below) being false or do we have a better way to check?

`const debug = (localStorage['org.5calls.debug'] === 'true');`

**Comment by oderby** [comment]
no, I don't think debug indicates prod vs dev.

I think a more reliable way is to look at `window.location.host === "5calls.org"`. The logic being that if the current js code is being run on a page served from 5calls.org, it must be prod. Anything else is not.

**Comment by schraj** [comment]
OK. I thought something like that would be better but hadn't seen it being used in the codebase yet.

**Comment by nickoneill** [comment]
done in 37b1ca695cb640c2b004721916041521153442cb
