### ISSUE TITLE
Make the location text / change location link look more obviously like a button

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#262]
We are discussing this for all platforms, as users continue to email us asking about how to change their location. A good first step is making that link look like a more traditional button so users know they can click on it.

**Comment by greggraf** [comment]
This may be my own idiosyncrasy but I would suggest that the "enter an address or zip code" text field be visible at all times.  When I first visited the site I had no idea that it was even there, or that anything location specific was happening.

There might be updates the placeholder text with feedback about the zip code lookup status, success or failure. The element could be disabled while lookup happens and feedback could happen above or below.

**Comment by nickoneill** [comment]
Yep, I like the idea of this being a general informational section about your location: "using your current location", "enter an address to get a representative" etc. It's not real clear as it is.

**Comment by nlsandler** [comment]
I can look into this one.

**Comment by oderby** [comment]
@nlsandler go for it! If you'd find it helpful, feel free to post a sketch or mock of what you're envisioning here to get feedback before implementing. Or, if it's easier to just implement and push a PR for review, that's fine too.

**Comment by nlsandler** [comment]
I'm not a designer, so I'd definitely like feedback! I was thinking we could put the button right under the location:
<img width="360" alt="change_location_button" src="https://cloud.githubusercontent.com/assets/1302114/24840390/2f5b6f98-1d21-11e7-85e9-96a1b714c9c5.png">

And the button could expand into the 'enter address' field, the same way the current one does:
<img width="363" alt="change_location_form" src="https://cloud.githubusercontent.com/assets/1302114/24840394/43573ac2-1d21-11e7-9f88-472f07d35025.png">

And the "Your location" text could change to show error messages or other feedback:
<img width="337" alt="form_error_msg" src="https://cloud.githubusercontent.com/assets/1302114/24840402/58ff518e-1d21-11e7-91ae-28b2f98c8561.png">

What do you think?

**Comment by nickoneill** [comment]
This looks great! Using the single line of text as either current location or error messaging is great. It's definitely clear what's going on in different states.

**Comment by nickoneill** [comment]
@nlsandler wrapped this in #292
