### ISSUE TITLE
Mobile app for iOS?

### ISSUE THREAD

**Issue by precipice** [5calls/5calls#27]
Would you take a mobile app for iOS if contributed? I'd be happy to help with that.

**Comment by nickoneill** [comment]
I'm on the fence here @precipice... I do like native experiences over web-based ones but we're not doing too much complex UI work here where it would be super valuable. Possibly in the future for a related project but not at the moment.

**Comment by precipice** [comment]
@nickoneill understood. I'll look for other ways to help. If you ever change your mind, feel free to ping me and I'd be happy to help. Thanks for the response and for the great site!
