### ISSUE TITLE
Change local number for WI-8

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#282]
From Twitter:

> Hey there! You have @RepGallagher (WI-8)'s district phone incorrect (not in service). In GB: 9203013492 In Appleton: 9209039806

**Comment by oderby** [comment]
@nickoneill it's unclear which number is which. Currently, we provide only a single phone number for rep Gallagher: 920-380-0061. Are you saying we should remove that # and add the two provided above?

**Comment by nickoneill** [comment]
Yep, sounds like it. His website lists those two but not the one we have in our current list.

**Comment by nickoneill** [comment]
Doing this now
