### ISSUE TITLE
Photo for Brian Babin shows Lloyd Doggett

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#284]
If you enter the zip 77520 (texas), you get Brian Babin's name and contact info but a picture of Lloyd Doggett!

This URL is for BrianBabin, obviously, but google clearly shows that this is an image of Doggett.
https://5calls.org/photo/TX-BrianBabin

Looking at the request from Google Civic API, it looks like the correct URL is being returned for the office of Babin: https://www.congress.gov/img/member/114_rp_tx_36_babin_brian_200.jpg

**Comment by Demonico** [comment]
The page for [Babin](https://5calls.org/photo/TX-BrianBabin) now gives a 404 and consequently call pages just show a placeholder.
