### ISSUE TITLE
Meta details are double-encoded

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#290]
Looking like this:

`<meta itemprop="description" content="Trump&amp;#39;s proposed budget ends all federal support for Amtrak&amp;#39;s long-distance (LD) train services, claiming they &amp;#34;incur the vast majority of Amtrak&amp;#39;s operating losses.&amp;#34; These trains provide the only nat"/>`

**Comment by greggraf** [comment]
My instinct here (since I don't know that we can depend on the string already having been encoded once) would be to change this:
```
s.SetAttr("content", html.EscapeString(issue.Reason[:200]))
```
to
```
s.SetAttr("content", html.EscapeString(html.UnescapeString(issue.Reason[:200])))
```

**Comment by bradfitz** [comment]
A shorter way to write `html.EscapeString(html.UnescapeString(...))` is `...`.

**Comment by greggraf** [comment]
While it is true: `html.EscapeString(html.UnescapeString("5 &lt; 10"))`  is `"5 &lt; 10"`, `html.EscapeString(html.UnescapeString("5 < 10"))` is not `"5 < 10"` but rather `"5 &lt; 10"`

This could be used as a guard against double escaping and handle the case where a string may or may not be escaped already.

If, on the other hand, we *know* that the string is always pre escaped, we can remove `html.EscapeString` from  `SetAttr()`: 
``` s.SetAttr("content", issue.Reason[:200])```

Can we rely on issue reason already being escaped?

**Comment by nickoneill** [comment]
The airtable API returns unescaped text, we can rely on staying as-is because it's unlikely the issue writers will start manually escaping their text.

I'm happy doing a dance in go if it means we can assume text is already escaped on the frontend. That sounds like the right thing to do here.

**Comment by nickoneill** [comment]
Excellent, thanks!
