### ISSUE TITLE
Investigate if any quick changes can make app startup faster

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#295]
The web app takes just enough time to start up that we see the non-js page "5 calls will be right back" for just a touch too long. It can be a bit jarring, particularly with the spanish version of the site.

It would be good to take a look at how we load the site and see what could potentially be optimized for some quick speed gains. We haven't really checked this since the base choo app was originally deployed so there might be some obvious things we can do to improve.

**Comment by oderby** [comment]
Note, startup timing and ordering may change significantly with #260, so that timeline should be factored into any work proposed here.

**Comment by oderby** [comment]
Do we want anyone to dive into this now @nickoneill? (Thinking of timing with migration)

**Comment by nickoneill** [comment]
Nope, not for choo now.

**Comment by nickoneill** [comment]
React makes this a hell of a lot faster
