### ISSUE TITLE
Fix zip/address lookup for Townhall data

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#307]
Previous solution used a large NPM module to do zip -> lat/lng lookups, which was a pain in development (es2040 translation takes more than a minute every time) and made the shipped app.js >5mb. I'm also not sure this solution supported distances from addresses.

We could potentially do a gmaps API geocoding lookup on address/zip while loading the townhall data in the background.

To start, revert this commit: 0de98b5e2d0a70f18f1d4d2de9a064455de38f2a

**Comment by oderby** [comment]
Fixed in #314 right?

**Comment by murribu** [comment]
yes
