### ISSUE TITLE
Keep main issues in sidebar when navigating from home

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#329]
Since the advent of our categorized More Issues page, the sidebar has been showing issues that are in the same category as the selected issue. This means it's hard to just call on the main issues on the front page, you have to call, go back, call, go back, etc.

Let's investigate how it would work if you only saw the issues in this category if you followed a link from the More Issues page, and kept seeing the main page issues when you navigate via the front page.

**Comment by Demonico** [comment]
After playing around with the site a bit, it looks like this bug was resolved already or needs clarification.

**Comment by nickoneill** [comment]
Hey @Demonico, sometimes we're bad at cleaning up old issues. You're right on this one, it's been adjusted and this is no longer relevant. Let me know if you need some guidance on what might be a good fit to work on.
