### ISSUE TITLE
Add redirect for the newsletter

### ISSUE THREAD

**Issue by bryansills** [5calls/5calls#330]
As mentioned [here](https://github.com/5calls/android/pull/86#discussion_r124419047), there should be a URL at [https://5calls.org/newsletter](https://5calls.org/newsletter) that redirects to the current newsletter signup page. This will allow the project to change the newsletter provider without breaking the link in the apps.

**Comment by nickoneill** [comment]
Thanks @bryansills! Also invited to slack
