### ISSUE TITLE
Results button labels are not loading

### ISSUE THREAD

**Issue by stevegrunwell** [5calls/5calls#342]
When visiting https://5calls.org/issue/rec1JDCdyFCYYYFu9 this morning, the text on the buttons below the "Enter your call result to get the next call:" header are not loading (FWIW, using postal code 43230):

![Screenshot of buttons in Google Chrome](https://user-images.githubusercontent.com/233836/30065580-5f8546cc-9223-11e7-809d-1dafface116d.png)

![Screenshot of buttons in Apple Safari](https://user-images.githubusercontent.com/233836/30065581-5f87e9f4-9223-11e7-9d27-b531b9619f54.png)

![Screenshot of buttons in Mozilla Firefox](https://user-images.githubusercontent.com/233836/30065603-723f3f02-9223-11e7-97a5-6726e5246a0a.png)

The problem appears to persist across browsers (tested on Chrome 60.0.3112.113, Safari 10.1.2 (12603.3.8), and Firefox 55.0.3, all on macOS 10.12.6). No errors are appearing in the JavaScript console for any of the three tested browsers.

**Comment by nickoneill** [comment]
Thanks @stevegrunwell! We deployed some changes last night, looks like we have an issue with the translation strings.

**Comment by cdoremus** [comment]
This happened to me once too, but then it went away. Could it be some sort of caching issue?

**Comment by nickoneill** [comment]
I think so - look at the requests, one is being made for town halls which means it's the old html/js. And the new locales files changes the outcome string format.

I was about to say "interesting that the html is being cached so long" and then I realized it's probably being cached by the go server after doing that fake-isomorphic rewrite. I kicked over call serve, it should start with a fresh cache now.

**Comment by nickoneill** [comment]
This should be resolved now @stevegrunwell - let me know if you see it again.

**Comment by stevegrunwell** [comment]
Can confirm the buttons are appearing with proper labels now. Thanks for getting on this so quickly!!

**Comment by nickoneill** [comment]
Awesome, thanks for filing the report!
