### ISSUE TITLE
Support markdown for issues and scripts

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#348]
This is already partially done in the team context, we should make sure it's implemented for normal issues and scripts.

See the work for teams done on this branch: https://github.com/5calls/react-dev/tree/nick-group-fetch-contacts

**Comment by lnathanson** [comment]
This was mostly done already by Nick. I've submitted a PR to finish out this task.. https://github.com/5calls/5calls/pull/359

**Comment by nickoneill** [comment]
Thanks!
