### ISSUE TITLE
Location Change link on main page is broken

### ISSUE THREAD

**Issue by LisieRae** [5calls/5calls#36]
Clicking the link to Change my location does not do anything. This prevents the user from accessing any useful content.

Broken on Chrome and Safari, in regular and incognito modes, on Chrome on Android, and in the Facebook mobile browser.

**Comment by jauses** [comment]
I'm seeing a handful of JS errors including a `429 Too Many Requests` error from `ipinfo.io/json`. Seems to have exceeded the allowed number of API calls.

**Comment by LisieRae** [comment]
In the mean time, is there a way I can craft a url to get to the content?

**Comment by jauses** [comment]
Looks like, no. Issue URLs are hashed. I reloaded one from my browser history and the content failed to load due to these API errors. I'm going to open a separate issue for this. There should be some sort of fallback if the IP-sniffing API dies.

**Comment by nickoneill** [comment]
I'm guessing this is related to downtime, we'll handle the location change in the other thread.
