### ISSUE TITLE
image of Kamala Harris is broken 

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#368]
just got a user saying 
"FYI, there’s a photo of Diane Feinstein instead of Kamala Harris on pages for Senator Harris. It started appearing that way a few weeks ago."

i checked, and instead of that, i get no image for Kamala Harris--DiFi looks fine. 

![image](https://user-images.githubusercontent.com/1844087/33790223-23fca0d2-dc33-11e7-90a4-fdc8602818b0.png)

**Comment by nickoneill** [comment]
Thanks! Covered this in #363
