### ISSUE TITLE
No fallback when ipinfo.io API fails

### ISSUE THREAD

**Issue by jauses** [5calls/5calls#37]
Related to Issue #36 Is it possible to offer some sort of fallback (i.e. manual entry of zip code, cached issue/call scripts) if the ipinfo.io API fails. Right now, the site is completely broken because the allowed number of API calls has been exceeded.

**Comment by jauses** [comment]
Another thought is to use native browser location services rather than rely on a commercial, third-party API.

**Comment by nickoneill** [comment]
I would love to pull browser location as a replacement for ipinfo.io - we get something like 1000 free requests per day which we go through in next to no time...

Alternatively, I'm happy to pay for a geocoding service as a first pass for people's location. The problem is that we'd have to pay quite a lot of $$$ for ipaddr.io to cover all of our users. I don't know the alternatives, I just picked that one out of a hat when setting up.

**Comment by tkompare** [comment]
I work with jauses. There is https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation to get coordinates. Then there comes the question of how to turn that into a postal code. There are a few alternatives:

1. https://geoservices.tamu.edu/Services/ReverseGeocoding/About/ - Might be worth a contact. I do not know their use policy.
2. https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse I know they have a few tier and paid after a certain number of requests per time period.

I'm guessing there are others, but there are the two that popped out in my mind.

**Comment by jauses** [comment]
This might be an option. Haven't dug in to it, but it claims to attempt to grab geolocation via HTML 5 first and then uses IP address as a fallback via the Google Maps API. http://onury.github.io/geolocator/

**Comment by nickoneill** [comment]
We don't need a postal code specifically, in fact I prefer something with more accuracy. We can pass coordinates directly from geolocation.

Here's the user experience I'd like to see: ask for geolocation on the first visit right away. For subsequent visits, provide a little geolocation icon in the change location field that will ask for geolocation again. And manually setting an address in the input field should always override the geolocation.

**Comment by jauses** [comment]
I'm mostly a front-end dev, but will see if I can get something working. If not, someone with better programming chops should feel free to hop on this.

**Comment by nickoneill** [comment]
@jauses The location stuff is all on the front end :)

Also, I'm getting in contact with the ProgCode.co team... they're working on some custom backends doing exactly this (see https://github.com/msimonborg/phone-your-rep-api) though supporting a large amount of users running through this might be difficult.

**Comment by agjohnson** [comment]
Also perhaps worth mentioning here: maxmind geolite2 lookup could replace an API call for geoip lookup. This would be implemented on the backend in the issues lookup API call and only used if the user has not specified a location and their browser has disallowed/disabled geo location. I'll let someone else make a call if this is worth the effort however.

**Comment by nickoneill** [comment]
Between browser location and ipinfo, I think we're good on sources here
