### ISSUE TITLE
Verify as a Brave Publisher

### ISSUE THREAD

**Issue by rupl** [5calls/5calls#370]
People mostly use 5calls.org to read scripts while calling various representatives or other public servants. This time can be turned into money to fund the site infrastructure by registering as a Brave Publisher: https://publishers.basicattentiontoken.org/

After registering as a publisher, visitors who use Brave and have opted into this payment system will make a monthly automated donation based on number of page loads and total session durations. The donations can be automatically turned into a large variety of fiat and digital currencies.

Establishing the site as a verified publisher is quite simple. A file in the top-level `.well-known` directory is all you need. The ROI will be small at first, but hopefully as Brave becomes more popular the returns will make an impact on your budget.

**Comment by nickoneill** [comment]
Interesting @rupl! I remember hearing about the original BAT sale but I hadn't considered it in conjunction with 5 Calls as a publisher.

I signed up and verified via DNS. It'll be interesting to see how many people visit 5 Calls that support Brave/BAT

**Comment by rupl** [comment]
Cool! I use Brave every time, I'll keep an eye out and close this once the domain displays as verified.

**Comment by rupl** [comment]
I don't know if it was an issue with my browser but I finally noticed the verified logo as of today. Issue is already closed but I didn't want you to think I forgot ;)

**Comment by nickoneill** [comment]
Awesome! I linked everything up a few days after your initial ticket, but I'm not sure if the browser looks at DNS records itself for verification or if it gets a centralized list. Either way, looks like we're good to go.

Thanks for bringing this up!
