### ISSUE TITLE
Most features currently broken

### ISSUE THREAD

**Issue by roadriverrail** [5calls/5calls#38]
No call list, and clicking on most links does nothing.  Here's the error report from my Chrome developer console:

https://ipinfo.io/json Failed to load resource: the server responded with a status of 429 (Too Many Requests)
https://5calls.org/report/ Failed to load resource: the server responded with a status of 502 ()
5calls.org/:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.receiveTotals (app.js:4)
    at Function.<anonymous> (app.js:1)
    at app.js:2
    at app.js:2
    at u.run (app.js:1)
    at c (app.js:1)
https://5calls.org/issues/?address=30083 Failed to load resource: the server responded with a status of 502 ()

**Comment by nickoneill** [comment]
Yep, sorry about that. Back now.
