### ISSUE TITLE
number for Doug Jones isn't quite right. 

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#381]
Doug Jones’s correct phone number ends with a 4. 202-224-4124. The one in today’s action ends with 1. It asks for an extension and cuts off the caller.

**Comment by piebob** [comment]
another person wrote in 
I'm just writing to inform you that there is an error in the phone number that you provide for Doug Jones's Washington, D.C. office.

The number should be 202-224-4124

My source for this information: 
https://www.senate.gov/general/contact_information/senators_cfm.cfm?State=AL

**Comment by nickoneill** [comment]
This is fixed now
