### ISSUE TITLE
"Change" on mobile site doesn't work

### ISSUE THREAD

**Issue by JordanLyons** [5calls/5calls#39]
Great project! I live in Missoula, MT, 59801. The site can't detect my location on Chrome for Windows, Chrome on Android, or Safari on iOS. When I tap "change" on mobile devices, the site is unresponsive. Thanks for your help with this!

**Comment by nickoneill** [comment]
Hey @JordanLyons, we fixed an issue earlier this morning. You should be able to use it now.
