### ISSUE TITLE
NH Attorney General data is incorrect 

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#394]
The current Attorney General for the state of New Hampshire is Gordon MacDonald, Joseph Foster. 

when you google it, the promoted result from google is still Joseph Foster, but i checked on the NH gov website and confirmed the new name

**Comment by nickoneill** [comment]
Cool, these are input manually by us so this'll be an easy change.

**Comment by nickoneill** [comment]
Fixed this too.
