### ISSUE TITLE
Suggestion: Provide numbers for local offices in addition to DC offices

### ISSUE THREAD

**Issue by ebadgley** [5calls/5calls#40]
I've heard that it is often more effective to call a representative's local number (their home state/district) rather than the DC office, because they often have more staff locally focused on constituent outreach.  Is there a possibility of adding these numbers?  I have a list and can provide if it would be helpful.

**Comment by nickoneill** [comment]
Hi @ebadgley, we're talking about this in #12. We're definitely looking for a source for local offices, with the option of just finding them ourselves as a last resort.
