### ISSUE TITLE
Update NYS Attorney General information

### ISSUE THREAD

**Issue by diyclassics** [5calls/5calls#404]
NYS Attorney General should be updated to Barbara Underwood (as of 5/8/18; cf. https://en.wikipedia.org/wiki/Barbara_Underwood) I could update and make the PR as necessary—just wanted to clarify which file(s) should be changed.

**Comment by nickoneill** [comment]
Thanks @diyclassics! AGs are in our data set (i.e. not coming from Google Civic) so we should be able to update this.

**Comment by diyclassics** [comment]
If I can help, let me know.

**Comment by nickoneill** [comment]
I swapped the contact info for Barbara Underwood - it looks like the site we previously got all the AG photos from - naag.org - is down? We'll have to find another source for our AG photos before they show up again.

**Comment by nickoneill** [comment]
Looks like it was just something transient, naag.org is back and I swapped the photo for Underwood
