### ISSUE TITLE
Kim Guadagno is incorrectly listed as NJ Lt Governor and Secretary of State

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#414]
Kim Guadagno was Lieutenant Governor and NJ Secretary of State, and no longer holds those positions in the current administration. 
current NJ Lieutenant Governor is Sheila Oliver, current NJ Secretary of State is Tahesha Way.

**Comment by nickoneill** [comment]
I just fixed this the other day... maybe I missed the relevant zendesk ticket? We don't have the LT Gov position anywhere on the site.
