### ISSUE TITLE
Too much blue

### ISSUE THREAD

**Issue by damir** [5calls/5calls#421]
It is hard to navigate around because almost everything is blue - links, lists, headers, text ...
Please make links stand out with their own color and/or style.

**Comment by nickoneill** [comment]
Hi @damir, totally agree. We're moving to black text color shortly here to distinguish between links (probably still blue) and just text.

Anything else you noticed that could be switched from blue?

**Comment by aholachek** [comment]
I think this has been mostly fixed with the typography updates, I just opened up a more focused issue for blue on the call success page
