### ISSUE TITLE
NC Rep Robert Pittenger -- local numbers. 

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#427]
Representative Rober Pittenger's (R-NC) first local office number onsite is for his Mooresville office at 116 Morlake Dr, Mooresville NC 28117. The second is for his Charlotte office at 5970 Fairview Rd, Suite 430, Charlotte NC 28210.

**Comment by kamoh** [comment]
What's the change required here? It's unclear if any numbers are incorrect or what the new ones are.

**Comment by nickoneill** [comment]
Not sure, there might be no actionable info here. If they're verified as correct than we can close this.

**Comment by nickoneill** [comment]
Any update on this?

**Comment by kamoh** [comment]
Not sure - I'd maybe close this out if there isn't a clear action to take.
