### ISSUE TITLE
Using Prettier for code formatting

### ISSUE THREAD

**Issue by aholachek** [5calls/5calls#437]
This is very minor but it might make development more pleasant if [prettier](https://prettier.io/) is added. 

A [pre-commit hook](https://github.com/okonet/lint-staged) could run tslint --fix and prettier to ensure that code style was maintained with minimal work on the part of the developer

**Comment by nickoneill** [comment]
I am definitely all for this! I like having a single style that everyone can adhere to easily. We do have a `tslint` validation step in the tests, but it puts us in a situation where you can easily check in code that fails the tests without knowing the process upfront.

What would prettier do vs tslint alone?

Regardless of tooling choice, I do like the idea of a check during pre-commit.

**Comment by aholachek** [comment]
[I made a sample branch of what the code looks like after being run through prettier](https://github.com/5calls/5calls/compare/master...aholachek:prettier)

Prettier works in concert with tslint, it mostly takes care of really low-level formatting things. If you check out the diff you can see some of the changes -- I think everything looks neater and more consistent. When you're developing, if you use prettier, there's reduced cognitive load since you can completely ignore having to write nice spacing/alignment by hand because prettier will handle it for you.

**Comment by nickoneill** [comment]
I spotted a prettier plugin for vscode as well, which works great to format on save automatically.

**Comment by aholachek** [comment]
Ah that would be great, how do I go about getting added to the group?

**Comment by nickoneill** [comment]
Just sent you an invite email

**Comment by aholachek** [comment]
[closed with #441](https://github.com/5calls/5calls/pull/441)
