### ISSUE TITLE
If a representative is "unavailable" for a particular user, consider not showing that representative to the user for at least 5 minutes

### ISSUE THREAD

**Issue by dektar** [5calls/5calls#44]
"unavailable" may mean mailbox full or line disconnected. It doesn't make sense for the user to try that number again right away, even for a different issue.

**Comment by nickoneill** [comment]
This could definitely tie into the district office numbers we're working on... disabling those numbers and moving to the next one for this user.

**Comment by catherinetcai** [comment]
Maybe there can be alternative numbers listed? For example, my senator, Dianne Feinstein, has multiple numbers that she can be reached at. Her DC and Sacramento numbers were both unreachable, but for a while her San Diego office was open.

**Comment by Ipstenu** [comment]
There's also the option of faxing. 

https://faxzero.com/fax_senate.php
https://faxzero.com/fax_congress.php

We could link to that as an option?

**Comment by nickoneill** [comment]
Working on how to rotate multiple local office numbers on the backend
