### ISSUE TITLE
Help Documentation

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#451]
We're starting to use our help center on intercom to better explain complex issues to folks who visit the site, here are some topics we should consider writing about:

- [x] Why you only call some reps for some topics (
https://intercom.help/5calls/using-the-5-calls-website-and-apps/why-do-i-only-see-some-of-my-representatives)
- [x] How to set your location in the apps / site (https://intercom.help/5calls/using-the-5-calls-website-and-apps/how-do-i-set-my-location-on-5-calls)
- [x] Why you should only call your own representatives

**Comment by thebrengun** [comment]
It looks like this issue can be closed since the third article has been written [Why you should only call your own representatives](https://intercom.help/5calls/using-the-5-calls-website-and-apps/why-you-should-only-call-your-own-representative)

**Comment by nickoneill** [comment]
Thanks @thebrengun! Closing this
