### ISSUE TITLE
Call page tweaks

### ISSUE THREAD

**Issue by aholachek** [5calls/5calls#467]
A few thoughts about readability of the call page:

1. With updates, the page can get long and overwhelming. [Example](https://5calls.org/issue/end-the-government-shutdown-with-no-strings-attached-). I'd like to play around with only showing the most recent update in some sort of expandable banner component (that could be expanded to show older updates). Another quick-and-dirty other solution would be to limit the height of that text area and add a click-to-expand button.
2. 
![screen shot 2019-01-22 at 9 53 18 am](https://user-images.githubusercontent.com/3680488/51543557-d3f53400-1e2b-11e9-90bb-6f39e8697bd9.png)
I'd like to remove any text that is not directly related to the script from the script area (e.g. *if leaving a message*) since it's confusing, I would put it underneath instead.

3. I personally would love a script header that said something like **Your call script: feel free to read directly or give it your own spin**

4. I think this part could be aligned a little better if the image were smaller and anchored to the left:
![screen shot 2019-01-22 at 9 57 17 am](https://user-images.githubusercontent.com/3680488/51543693-246c9180-1e2c-11e9-9403-b45a361934ef.png)

I'm happy to work on any of these if they seemed reasonable (the update banner is obviously the toughest, i don't know how much would have to change about the way the text is sent over to make that happen).

**Comment by nickoneill** [comment]
Here was rebecca's feedback from slack:

> as far as updates — the shutdown call is very very unusual. most calls only get 1 update, maybe 2 in some cases.
> i’ve been thinking about how shitty the shutdown call looks bc of the updates but we never have calls that last a month like this with huge drama every few days
> i’m not sure your thoughts on moving the “if leaving a message” but was added based on hill staff requests. if that info isn’t in the vm they won’t the call.

1. We don't end up with huge update lists that frequently, so I don't think it's worth changing.
2. I agree that this should be outside of the script area, but the change has to be made on all platforms at once so we don't leave anyone without it (it's important information if folks are leaving vms). We don't have a ton of bandwidth on mobile development right now, so let's hold off and tackle this with another round of changes in the future.
3. I agree, let's clarify with a script header. The item that staffers note can be important is personal stories about what the issue means to them, so something like "Your call script: read directly or add your personal story" (I'm going to run this by folks on slack for actual wording)
4. Looks like you're getting this in another PR and it looks great there

**Comment by aholachek** [comment]
I think this has been partially resolved/ other changes are not necessary.
