### ISSUE TITLE
Enable linking directly to issues, without geographic state

### ISSUE THREAD

**Issue by jeffiel** [5calls/5calls#47]
Need URLs for issues, without the geographic call to action, for sharing on social media. If you share, and the link shows my senator, not yours, it's not helpful.

**Comment by nickoneill** [comment]
I don't believe it should share the incorrect contact as it is currently, but it will not show the issue itself if you don't have a location set and all contacts are location-based (i.e. all local senators and local house reps).

We should definitely fix, thanks for creating the issue! Let me know if you're interested in making this change.

**Comment by jeffiel** [comment]
I put the URL into an incognito window and got a "No issue here"  - It appears cookie state is important to the page to function?

For example: https://5calls.org/#issue/recyPsxELi8VZaixw

Don't know Go :( or I would dive in.

**Comment by nickoneill** [comment]
Yep, it's localstorage. Frontend is all javascript, react-ish framework called Choo.

Issues are coming back from the server OK but without a location set, the issue won't appear because they have all local contacts. The improvement would be this: show the issue and reason if linked to directly with a big CTA for adding your location instead of the contact view.

**Comment by jeffiel** [comment]
I think that would be a great way to handle this situation. Will enable social sharing.

**Comment by agjohnson** [comment]
It seems that geo ip lookup should ensure that issues are requested with an address for almost all requests. I can put together a patch on this, but I believe this will mostly be a defensive measure -- if geo ip lookup starts failing, etc.

**Comment by nickoneill** [comment]
@agjohnson We have geoip lookup right now (albeit only a small percentage of requests make it through before our daily quota is exhausted) but what we learned is that a) it's not exact for many connections and b) it's expensive for a significant quantity of requests.

There's a PR right now that prioritizes browser location which should alleviate the issue a bit but I still believe we should be showing all issues to all users before they enter a locatiton.

**Comment by imaflamingo** [comment]
yeah sounds good to show all issues to users.  On my phone I could see many issues before entering my zip code, but on my laptop I could only see one issue before I entered my zip code.  Would be nice for new users to immediately see whole list of issues before entering zip code.

**Comment by agjohnson** [comment]
@nickoneill roger. This sounds like a good addition/the best UX. Raised another option for geo ip lookup in #37 as well.

Currently, running `master` locally, the view template shows "Set your location to view your representatives" if a hardcoded empty address is passed to the back end issues API request. This is the UX I'd expect here, so seems like this might be resolved already.

**Comment by nickoneill** [comment]
Yes, just resolved as of an hour ago! Closing for now
