### ISSUE TITLE
Improve button styles a la donate button

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#470]
From @aholachek:

> I think we really need a better, more consistent, set of modern looking buttons. I made a custom style for the "donate" button on hover but it's not quite consistent with the rest of the app. The button that goes from light blue to red on hover on the "change location" button looks pretty dated to my eyes.

> Maybe that's another high-impact small task -- to make primary, secondary, and outline button components that we can use throughout the app.

Fully agree. The new donate button on the header feels like a nice improvement, let's base our work on that as a starting point.

**Comment by aholachek** [comment]
I briefly went down a rabbit hole trying to get optional css modules set up for this before realizing that it's not really necessary, as much as I'd like to move over to some sort of css-in-js solution, I'll just do some edits of the current css for now for the buttons.

It did get me wondering, though, how you would feel about trying to migrate the code over to a non-ejected create-react-app v2? That handles typescript, sass, and css modules out of the box, and I bet would fix that source map issue as well. I don't know enough about the project to know if there are serious reasons that it's not feasible, but thought I might bring it up before spending more time thinking about the current setup.
