### ISSUE TITLE
Investigate react-snap deploy issues

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#489]
I merged the react-snap work into `staging` so I could deploy it to some percentage of the website traffic and the deploy ended up looking like this, with only one page crawled:

```
...
9:39:55 AM: The project was built assuming it is hosted at https://5calls.org/.
9:39:55 AM: You can control this with the homepage field in your package.json.
9:39:55 AM: The build folder is ready to be deployed.
9:39:55 AM: $ react-snap
9:39:59 AM: ✅  crawled 1 out of 1 (/)
9:39:59 AM: Done in 47.95s.
9:39:59 AM: Caching artifacts
9:39:59 AM: Started saving node modules
...
```

I tried running `yarn build` locally and it seems like it crawled everything successfully. Have you seen this result before @aholachek? I'm going to push a minor commit to see if it builds successfully this time, but I'd like to figure out what happened here too.

**Comment by nickoneill** [comment]
First step: this preview isn't loading because it's looking for a js file at 5calls.org when it should be looking at a path on the preview url. I'm diving down the Webpack upgrade hole right now to fix, but it's not directly related to react-snap.

But it also means this should behave fine, but only if it's deployed at 100% on the main site. I might sneak it in over the weekend rather than doing my normal small percentage updates.

**Comment by aholachek** [comment]
Ooh nice! 
It looks like the [base url can also be provided by an environment variable](https://github.com/stereobooster/react-snap/blob/97f231318eec8233de063ffc886133c7a2169dcc/run.js#L12), could you try passing in the staging url as `process.env.PUBLIC_URL`?

**Comment by aholachek** [comment]
Also, if the webpack updates fix the source map issue please let me know and I will try to debug the redux caching.

**Comment by nickoneill** [comment]
@aholachek webpack update is ready, let me know if the sourcemaps are back to normal again for you. They look good on my side.

**Comment by aholachek** [comment]
If I run `yarn run build` on current master and look at `build/static/js/main.*.map` it still appears to be a css source map, can you take a look and see if you see the same?

**Comment by nickoneill** [comment]
I checked this locally and on the site, and it appears to be correct now: https://5calls.org/static/js/main.c993a6b8.js.map

I had to upgrade a boatload of packages to get to webpack 4 - can you try nuking node_modules and re-yarning?

**Comment by aholachek** [comment]
Oh no, sorry, it works fine, I was just rebasing over `origin/master` rather than `upstream/master` so my branch was outdated. It looks great! I'm going to look into the redux hydration thing and the bundle size this afternoon.

**Comment by nickoneill** [comment]
After deploying a small code change, this happened again on the most recent deploy.

**Comment by nickoneill** [comment]
Changed concurrency to 1 in #507 but a subsequent deploy failed to crawl after that. I'm gonna ask them how best to debug.

**Comment by nickoneill** [comment]
Looking good so far in #511

**Comment by nickoneill** [comment]
First deployment from master was good, I'm resolving this now
