### ISSUE TITLE
index.html not finding linked files?

### ISSUE THREAD

**Issue by jberman5** [5calls/5calls#50]
Having trouble with the set up here.
Cloned the repo and installed everything from the requirements doc, and converted scss to css file but when I open the index.html file in the browser it can't find the linked files/folders.

changed `<link rel="stylesheet" href="/css/style.css">` to `<link rel="stylesheet" href="../css/style.css">` and that got read the css sheet but not getting everything else.

Should I be reorganizing files to match with the locations shown in the links? Or am I missing something?

Thanks in advance!

**Comment by nickoneill** [comment]
The raw files for editing are in `static` but when running `gulp` to put everything together, the site should be previewed from `app/static` - a copy of everything with the correct structure will be there. Are you using this index.html file?

**Comment by jberman5** [comment]
First time using Gulp, wasn't doing it quite right but I installed all the dependencies and its working now. Thanks!
