### ISSUE TITLE
Issue styles need a blockquote improvement

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#501]
Writing team has been using block quotes for these top-of-line updates. They could use a line or something visually to call them out at the top of the issue text.

<img width="862" alt="screen shot 2019-02-26 at 4 01 52 pm" src="https://user-images.githubusercontent.com/49688/53455590-e55bce00-39df-11e9-93f9-e09fbd3a08c0.png">

**Comment by aholachek** [comment]
How would you feel about something like this?

<img width="930" alt="screen shot 2019-02-28 at 8 19 52 pm" src="https://user-images.githubusercontent.com/3680488/53609762-6066e500-3b96-11e9-974f-2a1e05bb69a8.png">

**Comment by aholachek** [comment]
Or if that's too many blue lines on the site we could also do something lighter:
<img width="849" alt="screen shot 2019-02-28 at 8 23 08 pm" src="https://user-images.githubusercontent.com/3680488/53609824-b471c980-3b96-11e9-8ef8-606903206e6b.png">

**Comment by nickoneill** [comment]
The blue looks quite good here, and we're pretty light on the blue on the call page anyway so I don't think it's overwhelming.

**Comment by nickoneill** [comment]
Fixed in #509
