### ISSUE TITLE
Ohio-15 should be Steve Stivers, not Joyce Beatty

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#505]
Joyce Beatty is not my Congressperson. Steve Stivers (R- Ohio District 15) is the correct representative.

 Groveport, OH, 43125-1133

**Comment by piebob** [comment]
further info from the user:

"5calls.org is now ignoring the last 4 digits of my zip code, which is needed to connect me with my Congressman, Steve Stivers, OH District 15. 

My little town of Groveport is gerrymandered right down Main St. Just putting in 43125 connects me with Joyce Beatty. The entire zip code 43125-1133 is needed to connect me with Steve Stivers. Stivers’ staff won’t even take my calls or consider my postcards, if I don’t include my last four digits. This has happened to me before with 5calls and, thankfully, your group was able to reset my information. Sorry, this is so confusing and it’s definitely not your fault. We blame gerrymandering and we think Ohio’s GOP is purposely trying to confuse us!"

so i'm not sure if this is actually broken or not--she's getting steve stivers with her 4-digit zip extension, but stivers won't talk to her :)

**Comment by nickoneill** [comment]
OK, this should be resolved now, they should get Stivers for both of those inputs.
