### ISSUE TITLE
Update Senator Doug Jones' photo

### ISSUE THREAD

**Issue by LaughingGiraffe** [5calls/5calls#508]
Alabama Senator Doug Jones goes by his middle name, not his first name Gordon.  Also, the picture you have for him is unflattering, can you please find another portrait?

**Comment by nickoneill** [comment]
Thanks @LaughingGiraffe! I know we have both names in the database, I'll investigate to see if we're picking the wrong one.

**Comment by LaughingGiraffe** [comment]
https://www.cbsnews.com/news/bending-toward-justice-senator-doug-jones-racism-and-birmingham-church-bombing/
Doug Jones is a person of integrity and character.  Please find a better picture to represent him.  I will reach out to his staff and see if they can provide a portrait.

**Comment by nickoneill** [comment]
Please let me know if they can provide one @LaughingGiraffe . We have to use photos with the proper license, so we can't just pick any one off the internet. If they can provide a photo under the public domain I'm happy to use it instead.

**Comment by LaughingGiraffe** [comment]
OK I just sent them an email.  Let's see if they answer!  I'd love to have this man re-elected.

**Comment by LaughingGiraffe** [comment]
Hi Nick!  I found this photo on Doug Jones' website.  I cropped just his head, if you think that will be more suitable.  [https://www.jones.senate.gov/imo/media/image/jones-press-portrait.jpg](url)

![jones-press-portrait (2)](https://user-images.githubusercontent.com/48146740/54164031-1e0c9600-4429-11e9-910f-55aaba09b883.jpg)

**Comment by LaughingGiraffe** [comment]
I just checked and his name is still listed on 5 Calls as "Gordan Jones."  Please do change this to "Doug Jones."
Here is his Senate website:  https://www.jones.senate.gov/about

**Comment by nickoneill** [comment]
Fixed the name, I'll work on getting the new image in soon.

**Comment by nickoneill** [comment]
Photo was updated here a while back
