### ISSUE TITLE
Add "source" parameter to track whether calls were made from web, Android App, or other

### ISSUE THREAD

**Issue by dektar** [5calls/5calls#51]
It'd be cool to add a "source" parameter to the POST request which allows the server to track the number of calls sent from each source - Android app, web, etc.

**Comment by nickoneill** [comment]
Also, another param to ignore requests when they're from test builds.

**Comment by mccarron** [comment]
+1 that @nickoneill

**Comment by mergesort** [comment]
Sounds like something you might want a header for, rather than a parameter. Any thoughts on that?

**Comment by nickoneill** [comment]
For source or ignore or both @mergesort ?

**Comment by nickoneill** [comment]
Source feels like it belongs as a param, but a more general TESTING header might be useful in all sorts of cases

**Comment by mccarron** [comment]
Agree a testing header would be better applied across all APIs.

**Comment by mergesort** [comment]
I meant to adding `source` as a header on every network request, not tied to a specific endpoint, to allow tracking where requests come from more easily.

**Comment by mergesort** [comment]
You could actually set the `source` header to be `test` when running your tests, and then you'd be able to have the server ignore requests as necessary as well.

**Comment by nickoneill** [comment]
Oooh, I like less code. This could work nicely.

@dektar are headers just as easy as params for android?

**Comment by dektar** [comment]
Looks like its only a few lines more code than a URL parameter! Fine with me.
