### ISSUE TITLE
Redirect www -> non-www site

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#52]
since they have different localstorage caches 🙄

**Comment by oderby** [comment]
Is this still a problem? I can't reproduce (or I'm not following correct steps to reproduce, or I'm totally misunderstanding the bug). When I load www.5calls.org in a browser, I am automatically redirected to 5calls.org - seems like the desired behavior.

**Comment by nickoneill** [comment]
Yeah, definitely stays on www for me. This is an nginx configuration thing I need to do :/

**Comment by nickoneill** [comment]
This is actually just a thing we need to do in the backend now

**Comment by nickoneill** [comment]
This is done because we're on netlify!
