### ISSUE TITLE
wrong photo for Joe Cunningham SC-1

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#521]
the profile picture for Representative Joe Cunningham (SC) is actually Senator Tim Scott (SC) (previous rep for SC-1, now senator).

**Comment by kamoh** [comment]
@nickoneill are these types of issues with wrong data due to bad responses from google civic?

**Comment by nickoneill** [comment]
This is from our data, but I haven't figured out a great way to make it so everyone can contribute yet. Ideally it'll just be a google doc, lemme work on it and figure out how we can open it up for contributions.

**Comment by piebob** [comment]
the original reporter wrote back a couple of weeks ago (sorry, i was too distracted by moving!) and said:
"now it shows Lindsey Graham instead of Tim Scott! Sometimes it shows the generic columns. "

wtf?

**Comment by nickoneill** [comment]
Huh, that is a weird one. But it's just photos, not info right?

**Comment by nickoneill** [comment]
This shouldn't happen anymore
