### ISSUE TITLE
Updated Rubio number

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#530]
> Today, I met with Marco Rubio’s local representatives. The correct ph# is 813-853-1099.
> The representative explained how Google has not updated the phone numbers for the politicians. 

We might have this right on platforms other than iOS, iOS is the only platform still on google civic numbers.

**Comment by piebob** [comment]
from the same user, 7 months later:
"The correct phone number for Senator Marco Rubio’s Tampa Bay, FL Office is 813-947-6288. It is staffed.

**Comment by nickoneill** [comment]
Fixed now
