### ISSUE TITLE
wrong rep for Michigan 48030, is showing Slotkin, should be Levin

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#531]
Hazel Park, Michigan 48030
should be Andy Levin, but is showing Elissa Slotkin. i checked this on House.gov. doesn't look like a split district, but i've asked the user to try their +4 digits.

**Comment by piebob** [comment]
a user in zipcode 48864  is showing the same issue. 
this issue is now over a year old.

**Comment by nickoneill** [comment]
48030 is fixed, 48864 should use an address
