### ISSUE TITLE
Check Wisco governor listing

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#536]
User suggested it was returning incorrectly for 54601

**Comment by kamoh** [comment]
Looks accurate in prod - it returns Tony Evers, the WI governor. Recommend to close.

![image](https://user-images.githubusercontent.com/3387824/72758877-a60b1280-3b99-11ea-9490-1e70ec720a9c.png)

**Comment by nickoneill** [comment]
Good looking photo for Evers
