### ISSUE TITLE
MA address is good enough to get their rep, but not their senators? 

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#547]
2 Cross Street, Gloucester, MA 01930 is not a split district, so it brings up the right Rep, but we claim there's not enough info to find the two senators. what's up with that? 

![image](https://user-images.githubusercontent.com/1844087/62726742-c4ef6100-b9cc-11e9-98dc-0e5cd746d75c.png)

**Comment by kamoh** [comment]
This zip is pulling data correctly now, recommend to close.
