### ISSUE TITLE
Airtable schema

### ISSUE THREAD

**Issue by agjohnson** [5calls/5calls#55]
Is there a way to provide an Airtable schema creation script, or a snapshot of the Airtable database for development? I suppose I can infer this from the modeling if not?

**Comment by nickoneill** [comment]
Yes: anyone can sign up for read access to the test database here: https://airtable.com/invite/l?inviteId=invo1EhjdkkkdjcxX&inviteToken=94e26833a508997c003b8908eebe4bb1

And we can change to edit on a case-by-case basis. Feel free to put this in the readme as well.

**Comment by agjohnson** [comment]
Great. Added to the docs in #54. Closing this.
