### ISSUE TITLE
NC-03 data needs updating, walter jones died and greg murphy replaced him

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#551]
the seat is not vacant, here's the new info:

https://gregmurphy.house.gov/contact/offices 

DC Office
2333 Rayburn HOB
Washington, DC 20515
Phone: (202) 225-3415

Greenville Office
1105 Corporate Dr.
Suite C
Greenville, NC 27858
Phone: (252) 931-1003

 
Onslow Office
234 Northwest Corridor Blvd.
Jacksonville, NC 28540
(910) 937-6929

**Comment by nickoneill** [comment]
- updated sheets for greg's info
