### ISSUE TITLE
429 errors on attempting to get the IP address of requestor

### ISSUE THREAD

**Issue by alex** [5calls/5calls#58]
![screen shot 2017-01-29 at 11 33 55 pm](https://cloud.githubusercontent.com/assets/772/22413217/7fa3c892-e67b-11e6-983e-41a1a2964c3b.png)

**Comment by nickoneill** [comment]
Yep, running way outside of our ipinfo.io requests. We'll be removing this in favor of browser location shortly.

Thanks for the note!

**Comment by nickoneill** [comment]
Actually, it looks like our request limit for ipinfo might be bumped up a bit starting tomorrow. @capndesign this might be relevant to your interests as well?

**Comment by nickoneill** [comment]
Should be resolved after the new push
