### ISSUE TITLE
Michigan AG Dana Nessel number needs updating

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#587]
Dana Nessel of Michigan
primary phone: 517-335-7622

Lansing office:
G. Mennen Williams Building
525 W. Ottawa Street
P.O. Box 30212
Lansing, MI 48909

Detroit Office:
Cadillac Place, 10th Floor
3030 W. Grand Blvd., Ste 10-200
Detroit, MI 48202
Phone: 313-456-0240

**Comment by nickoneill** [comment]
updated
