### ISSUE TITLE
Maryland-7 needs updating to list Rep Kweisi Mfume (replaced Elijah Cummings)

### ISSUE THREAD

**Issue by piebob** [5calls/5calls#588]
(202) 225-4741

Washington, DC Office:
2163 Rayburn HOB
Washington, DC 20515
Phone: (202) 225-4741

 
Baltimore Office:
1010 Park Avenue
Suite 105
Baltimore, MD 21201
Phone: 202-225-4741

 
Catonsville Office:
754 Frederick Road
Catonsville, MD 21228
Phone: 410-818-2120

 
Ellicott City Office:
8267 Main Street
Room 102
Ellicott, MD 21043
Phone: 443-364-5413

**Comment by nickoneill** [comment]
fixed
