### ISSUE TITLE
"What's important to you?" fails to load in Ubuntu Chrome

### ISSUE THREAD

**Issue by leequarella** [5calls/5calls#62]
Google Chrome Version 48.0.2564.116 (64-bit)

![bug](https://cloud.githubusercontent.com/assets/879547/22429258/0918da34-e6d8-11e6-925c-6e43b3de1dad.png)

**Comment by nickoneill** [comment]
Thanks @leequarella, this might be the same as #43... glad you captured it in more detail here. Any time to take a look at what's actually going on here?

**Comment by nickoneill** [comment]
This should be fixed now with the upgrade to choo 4.1.0
