### ISSUE TITLE
Feature request: Rotating people to call

### ISSUE THREAD

**Issue by catherinetcai** [5calls/5calls#66]
First off, thanks for making 5calls. This is awesome.

I've noticed that using 5calls, I tend to get the senior senator of CA (Dianne Feinstein) for just about every issue. Feinstein's been unavailable for weeks. I also never see the junior senator of CA (Kamala Harris) show up in these. Not sure if it's because the data set hasn't been updated yet.

I'm also seeing my representative and senator come up for just about every single call, barring a few issues. I wonder if it would be possible to rotate through different people to call (maybe even different senators/representatives) once a user has called their senators/reps that day?

**Comment by rebeccakaufman** [comment]
Hi Catherine,

No, the new 2017 senators and reps haven't been added to the API yet. Working on a fix.

Calls are only tallied if you're a constituent, so calling into other states is meaningless (even if it feels good!) We are working on adding the district office numbers, so you can call both the DC office and then the local office. 

-Rebecca

**Comment by nickoneill** [comment]
Harris should be there now, checking others!

**Comment by nickoneill** [comment]
They should be in now
