### ISSUE TITLE
Better mobile phone support

### ISSUE THREAD

**Issue by thejbru** [5calls/5calls#7]
Love this idea and so loaded it up on my iPhone 6s with the idea that I'd use it from my phone to make the calls each day. The functionality on the phone, however, isn't particularly great. I'd like, for example, to tap on the issue and have the information for that issue take over the screen and then have the phone number itself able to be tapped to initiate the call. I think that most of these recommendations can be accomplished through styling, and I'm willing to work on that, but I'm having trouble parsing out where to make modifications that I can turn into pull requests. So a few pointers, please?

**Comment by nickoneill** [comment]
Sure thing @thejbru! Mobile is the least polished part of the site, for sure.

You should be able to get started by doing `npm install` in the repo directory, then `gulp` to start autocompliling all the assets and everything. Then if you edit the scss files in `static/scss` files, they'll be automatically published into `app/static`.

Let me know if you need any other help?

**Comment by thejbru** [comment]
Ah-ha. Was wondering where the link from `static/scss` to `app/static` was. Will have to get `gulp` running on my machine at home and then make some edits. Will hit you with a pull request when I have something worth contributing!
