### ISSUE TITLE
Was given wrong congressman based on address

### ISSUE THREAD

**Issue by mjoyce91** [5calls/5calls#70]
I was given the wrong congressman when I entered my address. I live somewhat close to my district's border. I'd prefer not to post my address here, so send me a private message if you'd like to re-create the issue.

This site correctly displays my congressman:
http://www.house.gov/representatives/find/

**Comment by nickoneill** [comment]
Thanks @mjoyce91, we're using the google civic API to make those decisions now so not a whole lot I can do about that. I will count this as +1 for developing our own representative district database :)
