### ISSUE TITLE
Add support for district (state) office numbers.

### ISSUE THREAD

**Issue by andrewhorvatits** [5calls/5calls#72]
As per Emily Ellsworth on twitter (referenced in one of the [sources](https://www.nytimes.com/2016/11/22/us/politics/heres-why-you-should-call-not-email-your-legislators.html) on why calling works) said the most effective thing is to call at the district office instead of the D.C. office ([source](https://twitter.com/editoremilye/status/797243849798074368?ref_src=twsrc%5Etfw)). 

It would be great if both numbers were presented or users had the option to see district numbers.

**Comment by nickoneill** [comment]
This is covered in #12, thanks for bringing it up. It's quite important.
