### ISSUE TITLE
Allow GET requests per issueID and candidateID to get full text on these items

### ISSUE THREAD

**Issue by dektar** [5calls/5calls#75]
It'd be nice for displaying user stats in Android if I could get the issue text and candidate name even many months after they were in the active issues list.

**Comment by nickoneill** [comment]
This is a better option than just passing back all issues and only showing "active" ones

**Comment by dektar** [comment]
For Android, this is no longer a concern, because I'm storing ID/Name mappings in a local database for stats. Feel free to close if no one else needs this.

**Comment by alexanderjrobinson** [comment]
This will be handy to support universal links in the app.

**Comment by nickoneill** [comment]
Yeah, this is useful for web as well. I'll hack on this a bit today.

**Comment by nickoneill** [comment]
We can get issue details at `/v1/issue/<issueid>`
