### ISSUE TITLE
"You've made all the calls for this issue" listed even when I haven't yet

### ISSUE THREAD

**Issue by dektar** [5calls/5calls#78]
I can click on an issue for which I have not made calls (no green check), and after the call response buttons I see the text "You've made all the calls for this issue."

Then I tried a hard refresh (ctrl-shift-r) and each issue now says "1 more person to call for this issue", no matter if I've called yet or not.

I'm not sure what is going on, but it seems the message is not always being applied correctly.

This is Chrome on Mac. Let me know if I can provide more info!

**Comment by nickoneill** [comment]
Thanks @dektar - I suspect we're not properly updating the contact index here? Definitely needs a closer look

**Comment by benjaffe** [comment]
I'm on it!

**Comment by benjaffe** [comment]
On second thought, this won't fix the issue of the contactsLeft not getting set to the proper value on page refresh... https://github.com/5calls/5calls/pull/154/commits/9633c0472582d805d62c33ac9ae123da1dc61b9d#diff-a3451754425c5f00165d6b58cdae1777R8

So the pull request fixes a related UI bug, but not the original issue. I'm leaving it attached to this issue though.

**Comment by benjaffe** [comment]
I've split the second part regarding refreshing off into issue #156, and simplifying this issue to simply being about the inconsistent UI during a single user session with no refreshes.

**Comment by nickoneill** [comment]
Perfect, I'll check it out
