### ISSUE TITLE
Script says "Senator" even for Representatives

### ISSUE THREAD

**Issue by pmaiorana** [5calls/5calls#8]
Total nitpick: I noticed that the script says "Senator's Name" even in situations where you may not be calling a senator but instead a congressional representative. Here's an example:

https://cloudup.com/cw6ZwsG4E3D

Ideally that would update dynamically based on the position of the person you're calling, but if not, something like "Congressperson's name" would be more accurate.

Thanks for making this! :)

**Comment by pmaiorana** [comment]
After poking around in the code a bit I'm realizing this may be a data issue -- this is for the "Oppose the repeal of the Affordable Care Act" script, if that wasn't clear from the screenshot.

And here's the URL if it's helpful, although I think it might be personalized to me (doesn't work Incognito): https://5calls.org/#issue/recjlaUIqNSp681yW

**Comment by nickoneill** [comment]
Small script issue, shouldn't happen again!
