### ISSUE TITLE
From iphone cannot click to dial which will affect usage

### ISSUE THREAD

**Issue by danielone** [5calls/5calls#82]
Phone numbers should be formatted in a way in the code that iPhone's safari browser can pick up that it is a number so that it recognized as such and is then clickable which makes it much easier to call rather than copying and pasting the number. 

I get the large format to make it clear but the line wrapping may be causing the issue so a smaller font size and ensuring proper html formatting will help

From a usability standpoint, users will likely engage less as it is more effort to copy & paste vs. click-to-dial

It looks like this is the format needed 
`<a href="tel:1-800-555-1212">1-800-555-1212</a>`
As per http://smallbusiness.chron.com/make-phone-number-clickable-iphone-users-30801.html

**Comment by ColemanCollins** [comment]
Just attempted this on an iPhone 6s with the latest Safari and Chrome with phone numbers that appear in the issue pages (big red ones below the rep names, assuming that's what you're talking about here).

Clicking on the phone number below my rep's name successfully launched the `tel` protocol and asks me to either 'call' or 'cancel,' as expected/desired. Using inspector on web, it looks like the numbers are formatted in the way you suggest. 

What specific browser and device combination are you use using that isn't working?

**Comment by danielone** [comment]
I'll try again - I was on iPhone 6 last week and the number were big and white but not clickable
If I see the issue, ill post pics

**Comment by ColemanCollins** [comment]
Rad, thanks!

**Comment by danielone** [comment]
Didn't see the issue anymore and looks like you have a nice new look already with a white background instead of blue for text so I think a lot easier to read and use. I probably used an older version?
Great work!

**Comment by nickoneill** [comment]
Yep, this looks fixed to me. Thanks for the report @danielone
