### ISSUE TITLE
Feature Request: dynamic call scripts.

### ISSUE THREAD

**Issue by issackelly** [5calls/5calls#85]
It would be really nice to have dynamic call scripts so I have to make fewer intepretations while I'm on the phone.

Good!

```
Hi, my name is [Name] and I'm a constituent from [City, State, Zip].

I’m calling to tell [Senator/Rep’s Name] that our community does not support Trump’s Muslim ban, and we expect [him/her] to take an immediate stand against this unjust executive order.

[Optional: add anything else you’d like here]

Thank you for your time.

[IF LEAVING A VOICEMAIL: please leave your entire home address to ensure your call is tallied]
```

Better?

```
Hi, my name is [Name] and I'm a constituent from [City, State, Zip].

I’m calling to tell Senator Feinstein that our community does not support Trump’s Muslim ban, and we expect her to take an immediate stand against this unjust executive order.

[Optional: add anything else you’d like here]

Thank you for your time.

[IF LEAVING A VOICEMAIL: please leave your entire home address to ensure your call is tallied]
```

Better still?

```
Hi, my name is Issac and I'm a constituent from Oakland, CA 94618

I’m calling to tell Senator Feinstein that our community does not support Trump’s Muslim ban, and we expect her to take an immediate stand against this unjust executive order.

[Optional: add anything else you’d like here, (ask about second issue)]

Thank you for your time.

[IF LEAVING A VOICEMAIL: please leave your entire home address to ensure your call is tallied]
```

**Comment by issackelly** [comment]
I could see storing my name, address, and zipcode in localStorage or a cookie. 
I could see the script area being an text box or ace editor so that I can make my adjustments before the phone call is made.

Being on the phone isn't always comfortable! Having a script is nice. You're doing great work.

**Comment by nickoneill** [comment]
Mentioned on slack and I'll reiterate here: this is great as long as we do it automatically based on the info supplied. Should be able to get a bunch of this via the civic api `normalizedInput` field, let me know if you need more in the API response.

**Comment by joshfeingold** [comment]
I think with this one it should be dependant.  If the app has the info, like the senator name, that def makes sense, but the individuals name, I think requires that the user add their info which is another step in the process to get them actually making an impact.  The less steps that better.

**Comment by jameshome** [comment]
See #19 for some related ideas, mostly covered here (closing that one out).

**Comment by samhavens** [comment]
Gender is a hiccup here. The scripts sometimes contain `[him/her]`, but that information doesn't seem to be available from the Civics API. For example, this shows up in this script:
```
Hi, my name is [Name] and I'm a constituent from [City, State, Zip].

I’m calling to tell [Senator/Rep’s Name] that our community does not support Trump’s Muslim ban,
and we expect [him/her] to take an immediate stand against this unjust executive order.

[Optional: add anything else you’d like here]

Thank you for your time.

[IF LEAVING A VOICEMAIL: please leave your entire home address to ensure your call is tallied]
```

A possible workaround is when filling in the script, replacing `[him/her]` with `them`. Other options are changing the scripts to remove gender references, or [inferring gender from name](https://www.npmjs.com/package/gender-inference) (which is honestly a terrible idea, I'm just trying to list all solutions I can think of).

**Comment by joshfeingold** [comment]
Workaround:  "I expect my representantive"

**Comment by samhavens** [comment]
Any issues here based on their position, or is that always appropriate?
-- 


Sam Havens   CTO
mobile: 818.590.0484
address: 23480 Park Sorrento 125B | Calabasas, CA 91302
web: carlabs.com
email: sam@carlabs.com

**Comment by nickoneill** [comment]
Nothing at the moment @samhavens, so you're safe there.

**Comment by nickoneill** [comment]
@bernardwang is currently working on improving what @samhavens started on in #150

**Comment by nickoneill** [comment]
V1 of this is done in #299!
