### ISSUE TITLE
Mobile view could use some love

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#9]
- [x] Styling is not great on small screens
- [x] clicking result buttons doesn't let you know there's a new contact
- [x] phone numbers don't tap-to-dial

**Comment by ivanoats** [comment]
I'm taking a look at the tap-to-dial issue now https://mobiforge.com/design-development/mobile-friendliness-101-adding-click-to-call-links-to-a-website

**Comment by ivanoats** [comment]
Thanks, Zach 👍

**Comment by nickoneill** [comment]
All set here for now
