### ISSUE TITLE
Consider adding personal stats

### ISSUE THREAD

**Issue by jameshome** [5calls/5calls#90]
From a friend:
"I'd really like to track how many calls I make that don't go through. Right now, if I hit Unavailable I get bumped to the next call. Would be nice to be able to hit Unavailable and see my count increment. I think it might also encourage people to be more persistent in trying to get through if they get "credit" for listening to the busy signal."

I generally wince at gamification, but this could be a good place for it.

**Comment by oderby** [comment]
Tracking this feature in #195
