### ISSUE TITLE
Change backend package name

### ISSUE THREAD

**Issue by josharian** [5calls/5calls#95]
If you do `go install` in `github.com/5calls/5calls/go`, you get a binary called `go`. If `$GOPATH/bin` is in your `$PATH`, as it is for many people, you can end up with the 5calls `go` binary taking precedence over the actual go command. :P

I will fix, just filing an issue for context and so I don't forget.

**Comment by nickoneill** [comment]
You want to break the backend out into its own project? That might make for a more sensible directory structure.

**Comment by josharian** [comment]
I'd like everything to live in a single repo, for sanity + atomic changes. I just want to do `git mv go fivecalls`. Waiting for there to be no outstanding backend PRs for this.

**Comment by oderby** [comment]
Still on your todo list @josharian (no rush, just cleaning up some issues)
