### ISSUE TITLE
Add JavaScript unit tests

### ISSUE THREAD

**Issue by cdoremus** [5calls/5calls#96]
This project needs test coverage and I'd like to start with JavaScript tests using Mocha. The normal convention for Mocha is to put tests in a 'test' folder, but I think that will be confusing since this repo does not only contain JavaScript, so people might expect Go tests to be in that folder too. What I propose to do is to use the convention of naming tests with a _test suffix, so, for example, callcount_test.js would test the callcount.js code.
I also plan on adding a 'test' task to gulpfile as part of this effort. The initial work will include updates to gulpfile and package.json (adding mocha, gulp_mocha, sinon and chai) and an initial unit test (callcount_test.js).

**Comment by nickoneill** [comment]
Looks like more info for this is in #131 now
